# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/dev/github/CMatchIteractiveFic

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/dev/github/CMatchIteractiveFic

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/dev/github/CMatchIteractiveFic/CMakeFiles /mnt/c/dev/github/CMatchIteractiveFic/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/dev/github/CMatchIteractiveFic/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named apx

# Build rule for target.
apx: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 apx
.PHONY : apx

# fast build rule for target.
apx/fast:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/build
.PHONY : apx/fast

# target to build an object file
AppMatch/AppMatch/AppMatch.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/AppMatch.o
.PHONY : AppMatch/AppMatch/AppMatch.o

# target to preprocess a source file
AppMatch/AppMatch/AppMatch.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/AppMatch.i
.PHONY : AppMatch/AppMatch/AppMatch.i

# target to generate assembly for a file
AppMatch/AppMatch/AppMatch.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/AppMatch.s
.PHONY : AppMatch/AppMatch/AppMatch.s

# target to build an object file
AppMatch/AppMatch/AssertationDefaultValue.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/AssertationDefaultValue.o
.PHONY : AppMatch/AppMatch/AssertationDefaultValue.o

# target to preprocess a source file
AppMatch/AppMatch/AssertationDefaultValue.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/AssertationDefaultValue.i
.PHONY : AppMatch/AppMatch/AssertationDefaultValue.i

# target to generate assembly for a file
AppMatch/AppMatch/AssertationDefaultValue.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/AssertationDefaultValue.s
.PHONY : AppMatch/AppMatch/AssertationDefaultValue.s

# target to build an object file
AppMatch/AppMatch/AssertationEngine.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/AssertationEngine.o
.PHONY : AppMatch/AppMatch/AssertationEngine.o

# target to preprocess a source file
AppMatch/AppMatch/AssertationEngine.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/AssertationEngine.i
.PHONY : AppMatch/AppMatch/AssertationEngine.i

# target to generate assembly for a file
AppMatch/AppMatch/AssertationEngine.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/AssertationEngine.s
.PHONY : AppMatch/AppMatch/AssertationEngine.s

# target to build an object file
AppMatch/AppMatch/AssertationVerbRelation.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/AssertationVerbRelation.o
.PHONY : AppMatch/AppMatch/AssertationVerbRelation.o

# target to preprocess a source file
AppMatch/AppMatch/AssertationVerbRelation.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/AssertationVerbRelation.i
.PHONY : AppMatch/AppMatch/AssertationVerbRelation.i

# target to generate assembly for a file
AppMatch/AppMatch/AssertationVerbRelation.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/AssertationVerbRelation.s
.PHONY : AppMatch/AppMatch/AssertationVerbRelation.s

# target to build an object file
AppMatch/AppMatch/AssertionValues.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/AssertionValues.o
.PHONY : AppMatch/AppMatch/AssertionValues.o

# target to preprocess a source file
AppMatch/AppMatch/AssertionValues.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/AssertionValues.i
.PHONY : AppMatch/AppMatch/AssertionValues.i

# target to generate assembly for a file
AppMatch/AppMatch/AssertionValues.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/AssertionValues.s
.PHONY : AppMatch/AppMatch/AssertionValues.s

# target to build an object file
AppMatch/AppMatch/BlockInstance.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/BlockInstance.o
.PHONY : AppMatch/AppMatch/BlockInstance.o

# target to preprocess a source file
AppMatch/AppMatch/BlockInstance.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/BlockInstance.i
.PHONY : AppMatch/AppMatch/BlockInstance.i

# target to generate assembly for a file
AppMatch/AppMatch/BlockInstance.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/BlockInstance.s
.PHONY : AppMatch/AppMatch/BlockInstance.s

# target to build an object file
AppMatch/AppMatch/BlockInterpreter.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/BlockInterpreter.o
.PHONY : AppMatch/AppMatch/BlockInterpreter.o

# target to preprocess a source file
AppMatch/AppMatch/BlockInterpreter.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/BlockInterpreter.i
.PHONY : AppMatch/AppMatch/BlockInterpreter.i

# target to generate assembly for a file
AppMatch/AppMatch/BlockInterpreter.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/BlockInterpreter.s
.PHONY : AppMatch/AppMatch/BlockInterpreter.s

# target to build an object file
AppMatch/AppMatch/CBase.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CBase.o
.PHONY : AppMatch/AppMatch/CBase.o

# target to preprocess a source file
AppMatch/AppMatch/CBase.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CBase.i
.PHONY : AppMatch/AppMatch/CBase.i

# target to generate assembly for a file
AppMatch/AppMatch/CBase.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CBase.s
.PHONY : AppMatch/AppMatch/CBase.s

# target to build an object file
AppMatch/AppMatch/CBlockDumpValues.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CBlockDumpValues.o
.PHONY : AppMatch/AppMatch/CBlockDumpValues.o

# target to preprocess a source file
AppMatch/AppMatch/CBlockDumpValues.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CBlockDumpValues.i
.PHONY : AppMatch/AppMatch/CBlockDumpValues.i

# target to generate assembly for a file
AppMatch/AppMatch/CBlockDumpValues.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CBlockDumpValues.s
.PHONY : AppMatch/AppMatch/CBlockDumpValues.s

# target to build an object file
AppMatch/AppMatch/CBlockInterpreterDecideBody.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CBlockInterpreterDecideBody.o
.PHONY : AppMatch/AppMatch/CBlockInterpreterDecideBody.o

# target to preprocess a source file
AppMatch/AppMatch/CBlockInterpreterDecideBody.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CBlockInterpreterDecideBody.i
.PHONY : AppMatch/AppMatch/CBlockInterpreterDecideBody.i

# target to generate assembly for a file
AppMatch/AppMatch/CBlockInterpreterDecideBody.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CBlockInterpreterDecideBody.s
.PHONY : AppMatch/AppMatch/CBlockInterpreterDecideBody.s

# target to build an object file
AppMatch/AppMatch/CInterpreter.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CInterpreter.o
.PHONY : AppMatch/AppMatch/CInterpreter.o

# target to preprocess a source file
AppMatch/AppMatch/CInterpreter.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CInterpreter.i
.PHONY : AppMatch/AppMatch/CInterpreter.i

# target to generate assembly for a file
AppMatch/AppMatch/CInterpreter.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CInterpreter.s
.PHONY : AppMatch/AppMatch/CInterpreter.s

# target to build an object file
AppMatch/AppMatch/CInterpreterKindTree.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CInterpreterKindTree.o
.PHONY : AppMatch/AppMatch/CInterpreterKindTree.o

# target to preprocess a source file
AppMatch/AppMatch/CInterpreterKindTree.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CInterpreterKindTree.i
.PHONY : AppMatch/AppMatch/CInterpreterKindTree.i

# target to generate assembly for a file
AppMatch/AppMatch/CInterpreterKindTree.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CInterpreterKindTree.s
.PHONY : AppMatch/AppMatch/CInterpreterKindTree.s

# target to build an object file
AppMatch/AppMatch/CInterpreterResolve.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CInterpreterResolve.o
.PHONY : AppMatch/AppMatch/CInterpreterResolve.o

# target to preprocess a source file
AppMatch/AppMatch/CInterpreterResolve.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CInterpreterResolve.i
.PHONY : AppMatch/AppMatch/CInterpreterResolve.i

# target to generate assembly for a file
AppMatch/AppMatch/CInterpreterResolve.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CInterpreterResolve.s
.PHONY : AppMatch/AppMatch/CInterpreterResolve.s

# target to build an object file
AppMatch/AppMatch/CMatch.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CMatch.o
.PHONY : AppMatch/AppMatch/CMatch.o

# target to preprocess a source file
AppMatch/AppMatch/CMatch.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CMatch.i
.PHONY : AppMatch/AppMatch/CMatch.i

# target to generate assembly for a file
AppMatch/AppMatch/CMatch.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CMatch.s
.PHONY : AppMatch/AppMatch/CMatch.s

# target to build an object file
AppMatch/AppMatch/CParseAux.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CParseAux.o
.PHONY : AppMatch/AppMatch/CParseAux.o

# target to preprocess a source file
AppMatch/AppMatch/CParseAux.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CParseAux.i
.PHONY : AppMatch/AppMatch/CParseAux.i

# target to generate assembly for a file
AppMatch/AppMatch/CParseAux.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CParseAux.s
.PHONY : AppMatch/AppMatch/CParseAux.s

# target to build an object file
AppMatch/AppMatch/CRelations.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CRelations.o
.PHONY : AppMatch/AppMatch/CRelations.o

# target to preprocess a source file
AppMatch/AppMatch/CRelations.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CRelations.i
.PHONY : AppMatch/AppMatch/CRelations.i

# target to generate assembly for a file
AppMatch/AppMatch/CRelations.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CRelations.s
.PHONY : AppMatch/AppMatch/CRelations.s

# target to build an object file
AppMatch/AppMatch/CResultMatch.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CResultMatch.o
.PHONY : AppMatch/AppMatch/CResultMatch.o

# target to preprocess a source file
AppMatch/AppMatch/CResultMatch.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CResultMatch.i
.PHONY : AppMatch/AppMatch/CResultMatch.i

# target to generate assembly for a file
AppMatch/AppMatch/CResultMatch.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CResultMatch.s
.PHONY : AppMatch/AppMatch/CResultMatch.s

# target to build an object file
AppMatch/AppMatch/CVariableGlobals.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CVariableGlobals.o
.PHONY : AppMatch/AppMatch/CVariableGlobals.o

# target to preprocess a source file
AppMatch/AppMatch/CVariableGlobals.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CVariableGlobals.i
.PHONY : AppMatch/AppMatch/CVariableGlobals.i

# target to generate assembly for a file
AppMatch/AppMatch/CVariableGlobals.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CVariableGlobals.s
.PHONY : AppMatch/AppMatch/CVariableGlobals.s

# target to build an object file
AppMatch/AppMatch/CpropertiesFunctions.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CpropertiesFunctions.o
.PHONY : AppMatch/AppMatch/CpropertiesFunctions.o

# target to preprocess a source file
AppMatch/AppMatch/CpropertiesFunctions.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CpropertiesFunctions.i
.PHONY : AppMatch/AppMatch/CpropertiesFunctions.i

# target to generate assembly for a file
AppMatch/AppMatch/CpropertiesFunctions.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CpropertiesFunctions.s
.PHONY : AppMatch/AppMatch/CpropertiesFunctions.s

# target to build an object file
AppMatch/AppMatch/CreateInstanceInterpreter.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CreateInstanceInterpreter.o
.PHONY : AppMatch/AppMatch/CreateInstanceInterpreter.o

# target to preprocess a source file
AppMatch/AppMatch/CreateInstanceInterpreter.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CreateInstanceInterpreter.i
.PHONY : AppMatch/AppMatch/CreateInstanceInterpreter.i

# target to generate assembly for a file
AppMatch/AppMatch/CreateInstanceInterpreter.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CreateInstanceInterpreter.s
.PHONY : AppMatch/AppMatch/CreateInstanceInterpreter.s

# target to build an object file
AppMatch/AppMatch/Equality.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/Equality.o
.PHONY : AppMatch/AppMatch/Equality.o

# target to preprocess a source file
AppMatch/AppMatch/Equality.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/Equality.i
.PHONY : AppMatch/AppMatch/Equality.i

# target to generate assembly for a file
AppMatch/AppMatch/Equality.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/Equality.s
.PHONY : AppMatch/AppMatch/Equality.s

# target to build an object file
AppMatch/AppMatch/FEnviroment.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/FEnviroment.o
.PHONY : AppMatch/AppMatch/FEnviroment.o

# target to preprocess a source file
AppMatch/AppMatch/FEnviroment.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/FEnviroment.i
.PHONY : AppMatch/AppMatch/FEnviroment.i

# target to generate assembly for a file
AppMatch/AppMatch/FEnviroment.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/FEnviroment.s
.PHONY : AppMatch/AppMatch/FEnviroment.s

# target to build an object file
AppMatch/AppMatch/InterpExecute.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/InterpExecute.o
.PHONY : AppMatch/AppMatch/InterpExecute.o

# target to preprocess a source file
AppMatch/AppMatch/InterpExecute.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/InterpExecute.i
.PHONY : AppMatch/AppMatch/InterpExecute.i

# target to generate assembly for a file
AppMatch/AppMatch/InterpExecute.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/InterpExecute.s
.PHONY : AppMatch/AppMatch/InterpExecute.s

# target to build an object file
AppMatch/AppMatch/InterpFunctionsCallcpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/InterpFunctionsCallcpp.o
.PHONY : AppMatch/AppMatch/InterpFunctionsCallcpp.o

# target to preprocess a source file
AppMatch/AppMatch/InterpFunctionsCallcpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/InterpFunctionsCallcpp.i
.PHONY : AppMatch/AppMatch/InterpFunctionsCallcpp.i

# target to generate assembly for a file
AppMatch/AppMatch/InterpFunctionsCallcpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/InterpFunctionsCallcpp.s
.PHONY : AppMatch/AppMatch/InterpFunctionsCallcpp.s

# target to build an object file
AppMatch/AppMatch/InterpreterListedFunctions.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/InterpreterListedFunctions.o
.PHONY : AppMatch/AppMatch/InterpreterListedFunctions.o

# target to preprocess a source file
AppMatch/AppMatch/InterpreterListedFunctions.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/InterpreterListedFunctions.i
.PHONY : AppMatch/AppMatch/InterpreterListedFunctions.i

# target to generate assembly for a file
AppMatch/AppMatch/InterpreterListedFunctions.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/InterpreterListedFunctions.s
.PHONY : AppMatch/AppMatch/InterpreterListedFunctions.s

# target to build an object file
AppMatch/AppMatch/InterpreterMatch.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/InterpreterMatch.o
.PHONY : AppMatch/AppMatch/InterpreterMatch.o

# target to preprocess a source file
AppMatch/AppMatch/InterpreterMatch.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/InterpreterMatch.i
.PHONY : AppMatch/AppMatch/InterpreterMatch.i

# target to generate assembly for a file
AppMatch/AppMatch/InterpreterMatch.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/InterpreterMatch.s
.PHONY : AppMatch/AppMatch/InterpreterMatch.s

# target to build an object file
AppMatch/AppMatch/InterpreterQuery.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/InterpreterQuery.o
.PHONY : AppMatch/AppMatch/InterpreterQuery.o

# target to preprocess a source file
AppMatch/AppMatch/InterpreterQuery.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/InterpreterQuery.i
.PHONY : AppMatch/AppMatch/InterpreterQuery.i

# target to generate assembly for a file
AppMatch/AppMatch/InterpreterQuery.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/InterpreterQuery.s
.PHONY : AppMatch/AppMatch/InterpreterQuery.s

# target to build an object file
AppMatch/AppMatch/ParseAssertationSecondary.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParseAssertationSecondary.o
.PHONY : AppMatch/AppMatch/ParseAssertationSecondary.o

# target to preprocess a source file
AppMatch/AppMatch/ParseAssertationSecondary.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParseAssertationSecondary.i
.PHONY : AppMatch/AppMatch/ParseAssertationSecondary.i

# target to generate assembly for a file
AppMatch/AppMatch/ParseAssertationSecondary.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParseAssertationSecondary.s
.PHONY : AppMatch/AppMatch/ParseAssertationSecondary.s

# target to build an object file
AppMatch/AppMatch/ParseDictionary.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParseDictionary.o
.PHONY : AppMatch/AppMatch/ParseDictionary.o

# target to preprocess a source file
AppMatch/AppMatch/ParseDictionary.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParseDictionary.i
.PHONY : AppMatch/AppMatch/ParseDictionary.i

# target to generate assembly for a file
AppMatch/AppMatch/ParseDictionary.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParseDictionary.s
.PHONY : AppMatch/AppMatch/ParseDictionary.s

# target to build an object file
AppMatch/AppMatch/ParseListAux.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParseListAux.o
.PHONY : AppMatch/AppMatch/ParseListAux.o

# target to preprocess a source file
AppMatch/AppMatch/ParseListAux.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParseListAux.i
.PHONY : AppMatch/AppMatch/ParseListAux.i

# target to generate assembly for a file
AppMatch/AppMatch/ParseListAux.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParseListAux.s
.PHONY : AppMatch/AppMatch/ParseListAux.s

# target to build an object file
AppMatch/AppMatch/ParseRelation.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParseRelation.o
.PHONY : AppMatch/AppMatch/ParseRelation.o

# target to preprocess a source file
AppMatch/AppMatch/ParseRelation.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParseRelation.i
.PHONY : AppMatch/AppMatch/ParseRelation.i

# target to generate assembly for a file
AppMatch/AppMatch/ParseRelation.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParseRelation.s
.PHONY : AppMatch/AppMatch/ParseRelation.s

# target to build an object file
AppMatch/AppMatch/ParseRelationWhen.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParseRelationWhen.o
.PHONY : AppMatch/AppMatch/ParseRelationWhen.o

# target to preprocess a source file
AppMatch/AppMatch/ParseRelationWhen.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParseRelationWhen.i
.PHONY : AppMatch/AppMatch/ParseRelationWhen.i

# target to generate assembly for a file
AppMatch/AppMatch/ParseRelationWhen.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParseRelationWhen.s
.PHONY : AppMatch/AppMatch/ParseRelationWhen.s

# target to build an object file
AppMatch/AppMatch/ParseVerbs.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParseVerbs.o
.PHONY : AppMatch/AppMatch/ParseVerbs.o

# target to preprocess a source file
AppMatch/AppMatch/ParseVerbs.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParseVerbs.i
.PHONY : AppMatch/AppMatch/ParseVerbs.i

# target to generate assembly for a file
AppMatch/AppMatch/ParseVerbs.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParseVerbs.s
.PHONY : AppMatch/AppMatch/ParseVerbs.s

# target to build an object file
AppMatch/AppMatch/Parser.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/Parser.o
.PHONY : AppMatch/AppMatch/Parser.o

# target to preprocess a source file
AppMatch/AppMatch/Parser.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/Parser.i
.PHONY : AppMatch/AppMatch/Parser.i

# target to generate assembly for a file
AppMatch/AppMatch/Parser.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/Parser.s
.PHONY : AppMatch/AppMatch/Parser.s

# target to build an object file
AppMatch/AppMatch/ParserDynamicDispatch.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParserDynamicDispatch.o
.PHONY : AppMatch/AppMatch/ParserDynamicDispatch.o

# target to preprocess a source file
AppMatch/AppMatch/ParserDynamicDispatch.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParserDynamicDispatch.i
.PHONY : AppMatch/AppMatch/ParserDynamicDispatch.i

# target to generate assembly for a file
AppMatch/AppMatch/ParserDynamicDispatch.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParserDynamicDispatch.s
.PHONY : AppMatch/AppMatch/ParserDynamicDispatch.s

# target to build an object file
AppMatch/AppMatch/ParserSelectorFunctional.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParserSelectorFunctional.o
.PHONY : AppMatch/AppMatch/ParserSelectorFunctional.o

# target to preprocess a source file
AppMatch/AppMatch/ParserSelectorFunctional.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParserSelectorFunctional.i
.PHONY : AppMatch/AppMatch/ParserSelectorFunctional.i

# target to generate assembly for a file
AppMatch/AppMatch/ParserSelectorFunctional.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParserSelectorFunctional.s
.PHONY : AppMatch/AppMatch/ParserSelectorFunctional.s

# target to build an object file
AppMatch/AppMatch/ParserStmt.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParserStmt.o
.PHONY : AppMatch/AppMatch/ParserStmt.o

# target to preprocess a source file
AppMatch/AppMatch/ParserStmt.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParserStmt.i
.PHONY : AppMatch/AppMatch/ParserStmt.i

# target to generate assembly for a file
AppMatch/AppMatch/ParserStmt.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParserStmt.s
.PHONY : AppMatch/AppMatch/ParserStmt.s

# target to build an object file
AppMatch/AppMatch/ParserTextEntry.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParserTextEntry.o
.PHONY : AppMatch/AppMatch/ParserTextEntry.o

# target to preprocess a source file
AppMatch/AppMatch/ParserTextEntry.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParserTextEntry.i
.PHONY : AppMatch/AppMatch/ParserTextEntry.i

# target to generate assembly for a file
AppMatch/AppMatch/ParserTextEntry.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParserTextEntry.s
.PHONY : AppMatch/AppMatch/ParserTextEntry.s

# target to build an object file
AppMatch/AppMatch/Parser_A.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/Parser_A.o
.PHONY : AppMatch/AppMatch/Parser_A.o

# target to preprocess a source file
AppMatch/AppMatch/Parser_A.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/Parser_A.i
.PHONY : AppMatch/AppMatch/Parser_A.i

# target to generate assembly for a file
AppMatch/AppMatch/Parser_A.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/Parser_A.s
.PHONY : AppMatch/AppMatch/Parser_A.s

# target to build an object file
AppMatch/AppMatch/Parser_Decide.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/Parser_Decide.o
.PHONY : AppMatch/AppMatch/Parser_Decide.o

# target to preprocess a source file
AppMatch/AppMatch/Parser_Decide.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/Parser_Decide.i
.PHONY : AppMatch/AppMatch/Parser_Decide.i

# target to generate assembly for a file
AppMatch/AppMatch/Parser_Decide.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/Parser_Decide.s
.PHONY : AppMatch/AppMatch/Parser_Decide.s

# target to build an object file
AppMatch/AppMatch/Parser_expression_match.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/Parser_expression_match.o
.PHONY : AppMatch/AppMatch/Parser_expression_match.o

# target to preprocess a source file
AppMatch/AppMatch/Parser_expression_match.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/Parser_expression_match.i
.PHONY : AppMatch/AppMatch/Parser_expression_match.i

# target to generate assembly for a file
AppMatch/AppMatch/Parser_expression_match.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/Parser_expression_match.s
.PHONY : AppMatch/AppMatch/Parser_expression_match.s

# target to build an object file
AppMatch/AppMatch/QueryItem.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/QueryItem.o
.PHONY : AppMatch/AppMatch/QueryItem.o

# target to preprocess a source file
AppMatch/AppMatch/QueryItem.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/QueryItem.i
.PHONY : AppMatch/AppMatch/QueryItem.i

# target to generate assembly for a file
AppMatch/AppMatch/QueryItem.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/QueryItem.s
.PHONY : AppMatch/AppMatch/QueryItem.s

# target to build an object file
AppMatch/AppMatch/RepresentationFunctions.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/RepresentationFunctions.o
.PHONY : AppMatch/AppMatch/RepresentationFunctions.o

# target to preprocess a source file
AppMatch/AppMatch/RepresentationFunctions.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/RepresentationFunctions.i
.PHONY : AppMatch/AppMatch/RepresentationFunctions.i

# target to generate assembly for a file
AppMatch/AppMatch/RepresentationFunctions.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/RepresentationFunctions.s
.PHONY : AppMatch/AppMatch/RepresentationFunctions.s

# target to build an object file
AppMatch/AppMatch/StaticDispatchFunctions.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/StaticDispatchFunctions.o
.PHONY : AppMatch/AppMatch/StaticDispatchFunctions.o

# target to preprocess a source file
AppMatch/AppMatch/StaticDispatchFunctions.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/StaticDispatchFunctions.i
.PHONY : AppMatch/AppMatch/StaticDispatchFunctions.i

# target to generate assembly for a file
AppMatch/AppMatch/StaticDispatchFunctions.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/StaticDispatchFunctions.s
.PHONY : AppMatch/AppMatch/StaticDispatchFunctions.s

# target to build an object file
AppMatch/AppMatch/stdafx.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/stdafx.o
.PHONY : AppMatch/AppMatch/stdafx.o

# target to preprocess a source file
AppMatch/AppMatch/stdafx.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/stdafx.i
.PHONY : AppMatch/AppMatch/stdafx.i

# target to generate assembly for a file
AppMatch/AppMatch/stdafx.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/stdafx.s
.PHONY : AppMatch/AppMatch/stdafx.s

# target to build an object file
AppMatch/AppMatch/testeLista.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/testeLista.o
.PHONY : AppMatch/AppMatch/testeLista.o

# target to preprocess a source file
AppMatch/AppMatch/testeLista.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/testeLista.i
.PHONY : AppMatch/AppMatch/testeLista.i

# target to generate assembly for a file
AppMatch/AppMatch/testeLista.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/testeLista.s
.PHONY : AppMatch/AppMatch/testeLista.s

# target to build an object file
AppMatch/AppMatch/testesParser.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/testesParser.o
.PHONY : AppMatch/AppMatch/testesParser.o

# target to preprocess a source file
AppMatch/AppMatch/testesParser.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/testesParser.i
.PHONY : AppMatch/AppMatch/testesParser.i

# target to generate assembly for a file
AppMatch/AppMatch/testesParser.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/testesParser.s
.PHONY : AppMatch/AppMatch/testesParser.s

# target to build an object file
AppMatch/AppMatch/testes_1.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/testes_1.o
.PHONY : AppMatch/AppMatch/testes_1.o

# target to preprocess a source file
AppMatch/AppMatch/testes_1.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/testes_1.i
.PHONY : AppMatch/AppMatch/testes_1.i

# target to generate assembly for a file
AppMatch/AppMatch/testes_1.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/testes_1.s
.PHONY : AppMatch/AppMatch/testes_1.s

# target to build an object file
AppMatch/AppMatch/testes_2.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/testes_2.o
.PHONY : AppMatch/AppMatch/testes_2.o

# target to preprocess a source file
AppMatch/AppMatch/testes_2.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/testes_2.i
.PHONY : AppMatch/AppMatch/testes_2.i

# target to generate assembly for a file
AppMatch/AppMatch/testes_2.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/testes_2.s
.PHONY : AppMatch/AppMatch/testes_2.s

# target to build an object file
AppMatch/AppMatch/testes_decide.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/testes_decide.o
.PHONY : AppMatch/AppMatch/testes_decide.o

# target to preprocess a source file
AppMatch/AppMatch/testes_decide.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/testes_decide.i
.PHONY : AppMatch/AppMatch/testes_decide.i

# target to generate assembly for a file
AppMatch/AppMatch/testes_decide.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/testes_decide.s
.PHONY : AppMatch/AppMatch/testes_decide.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... apx"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... AppMatch/AppMatch/AppMatch.o"
	@echo "... AppMatch/AppMatch/AppMatch.i"
	@echo "... AppMatch/AppMatch/AppMatch.s"
	@echo "... AppMatch/AppMatch/AssertationDefaultValue.o"
	@echo "... AppMatch/AppMatch/AssertationDefaultValue.i"
	@echo "... AppMatch/AppMatch/AssertationDefaultValue.s"
	@echo "... AppMatch/AppMatch/AssertationEngine.o"
	@echo "... AppMatch/AppMatch/AssertationEngine.i"
	@echo "... AppMatch/AppMatch/AssertationEngine.s"
	@echo "... AppMatch/AppMatch/AssertationVerbRelation.o"
	@echo "... AppMatch/AppMatch/AssertationVerbRelation.i"
	@echo "... AppMatch/AppMatch/AssertationVerbRelation.s"
	@echo "... AppMatch/AppMatch/AssertionValues.o"
	@echo "... AppMatch/AppMatch/AssertionValues.i"
	@echo "... AppMatch/AppMatch/AssertionValues.s"
	@echo "... AppMatch/AppMatch/BlockInstance.o"
	@echo "... AppMatch/AppMatch/BlockInstance.i"
	@echo "... AppMatch/AppMatch/BlockInstance.s"
	@echo "... AppMatch/AppMatch/BlockInterpreter.o"
	@echo "... AppMatch/AppMatch/BlockInterpreter.i"
	@echo "... AppMatch/AppMatch/BlockInterpreter.s"
	@echo "... AppMatch/AppMatch/CBase.o"
	@echo "... AppMatch/AppMatch/CBase.i"
	@echo "... AppMatch/AppMatch/CBase.s"
	@echo "... AppMatch/AppMatch/CBlockDumpValues.o"
	@echo "... AppMatch/AppMatch/CBlockDumpValues.i"
	@echo "... AppMatch/AppMatch/CBlockDumpValues.s"
	@echo "... AppMatch/AppMatch/CBlockInterpreterDecideBody.o"
	@echo "... AppMatch/AppMatch/CBlockInterpreterDecideBody.i"
	@echo "... AppMatch/AppMatch/CBlockInterpreterDecideBody.s"
	@echo "... AppMatch/AppMatch/CInterpreter.o"
	@echo "... AppMatch/AppMatch/CInterpreter.i"
	@echo "... AppMatch/AppMatch/CInterpreter.s"
	@echo "... AppMatch/AppMatch/CInterpreterKindTree.o"
	@echo "... AppMatch/AppMatch/CInterpreterKindTree.i"
	@echo "... AppMatch/AppMatch/CInterpreterKindTree.s"
	@echo "... AppMatch/AppMatch/CInterpreterResolve.o"
	@echo "... AppMatch/AppMatch/CInterpreterResolve.i"
	@echo "... AppMatch/AppMatch/CInterpreterResolve.s"
	@echo "... AppMatch/AppMatch/CMatch.o"
	@echo "... AppMatch/AppMatch/CMatch.i"
	@echo "... AppMatch/AppMatch/CMatch.s"
	@echo "... AppMatch/AppMatch/CParseAux.o"
	@echo "... AppMatch/AppMatch/CParseAux.i"
	@echo "... AppMatch/AppMatch/CParseAux.s"
	@echo "... AppMatch/AppMatch/CRelations.o"
	@echo "... AppMatch/AppMatch/CRelations.i"
	@echo "... AppMatch/AppMatch/CRelations.s"
	@echo "... AppMatch/AppMatch/CResultMatch.o"
	@echo "... AppMatch/AppMatch/CResultMatch.i"
	@echo "... AppMatch/AppMatch/CResultMatch.s"
	@echo "... AppMatch/AppMatch/CVariableGlobals.o"
	@echo "... AppMatch/AppMatch/CVariableGlobals.i"
	@echo "... AppMatch/AppMatch/CVariableGlobals.s"
	@echo "... AppMatch/AppMatch/CpropertiesFunctions.o"
	@echo "... AppMatch/AppMatch/CpropertiesFunctions.i"
	@echo "... AppMatch/AppMatch/CpropertiesFunctions.s"
	@echo "... AppMatch/AppMatch/CreateInstanceInterpreter.o"
	@echo "... AppMatch/AppMatch/CreateInstanceInterpreter.i"
	@echo "... AppMatch/AppMatch/CreateInstanceInterpreter.s"
	@echo "... AppMatch/AppMatch/Equality.o"
	@echo "... AppMatch/AppMatch/Equality.i"
	@echo "... AppMatch/AppMatch/Equality.s"
	@echo "... AppMatch/AppMatch/FEnviroment.o"
	@echo "... AppMatch/AppMatch/FEnviroment.i"
	@echo "... AppMatch/AppMatch/FEnviroment.s"
	@echo "... AppMatch/AppMatch/InterpExecute.o"
	@echo "... AppMatch/AppMatch/InterpExecute.i"
	@echo "... AppMatch/AppMatch/InterpExecute.s"
	@echo "... AppMatch/AppMatch/InterpFunctionsCallcpp.o"
	@echo "... AppMatch/AppMatch/InterpFunctionsCallcpp.i"
	@echo "... AppMatch/AppMatch/InterpFunctionsCallcpp.s"
	@echo "... AppMatch/AppMatch/InterpreterListedFunctions.o"
	@echo "... AppMatch/AppMatch/InterpreterListedFunctions.i"
	@echo "... AppMatch/AppMatch/InterpreterListedFunctions.s"
	@echo "... AppMatch/AppMatch/InterpreterMatch.o"
	@echo "... AppMatch/AppMatch/InterpreterMatch.i"
	@echo "... AppMatch/AppMatch/InterpreterMatch.s"
	@echo "... AppMatch/AppMatch/InterpreterQuery.o"
	@echo "... AppMatch/AppMatch/InterpreterQuery.i"
	@echo "... AppMatch/AppMatch/InterpreterQuery.s"
	@echo "... AppMatch/AppMatch/ParseAssertationSecondary.o"
	@echo "... AppMatch/AppMatch/ParseAssertationSecondary.i"
	@echo "... AppMatch/AppMatch/ParseAssertationSecondary.s"
	@echo "... AppMatch/AppMatch/ParseDictionary.o"
	@echo "... AppMatch/AppMatch/ParseDictionary.i"
	@echo "... AppMatch/AppMatch/ParseDictionary.s"
	@echo "... AppMatch/AppMatch/ParseListAux.o"
	@echo "... AppMatch/AppMatch/ParseListAux.i"
	@echo "... AppMatch/AppMatch/ParseListAux.s"
	@echo "... AppMatch/AppMatch/ParseRelation.o"
	@echo "... AppMatch/AppMatch/ParseRelation.i"
	@echo "... AppMatch/AppMatch/ParseRelation.s"
	@echo "... AppMatch/AppMatch/ParseRelationWhen.o"
	@echo "... AppMatch/AppMatch/ParseRelationWhen.i"
	@echo "... AppMatch/AppMatch/ParseRelationWhen.s"
	@echo "... AppMatch/AppMatch/ParseVerbs.o"
	@echo "... AppMatch/AppMatch/ParseVerbs.i"
	@echo "... AppMatch/AppMatch/ParseVerbs.s"
	@echo "... AppMatch/AppMatch/Parser.o"
	@echo "... AppMatch/AppMatch/Parser.i"
	@echo "... AppMatch/AppMatch/Parser.s"
	@echo "... AppMatch/AppMatch/ParserDynamicDispatch.o"
	@echo "... AppMatch/AppMatch/ParserDynamicDispatch.i"
	@echo "... AppMatch/AppMatch/ParserDynamicDispatch.s"
	@echo "... AppMatch/AppMatch/ParserSelectorFunctional.o"
	@echo "... AppMatch/AppMatch/ParserSelectorFunctional.i"
	@echo "... AppMatch/AppMatch/ParserSelectorFunctional.s"
	@echo "... AppMatch/AppMatch/ParserStmt.o"
	@echo "... AppMatch/AppMatch/ParserStmt.i"
	@echo "... AppMatch/AppMatch/ParserStmt.s"
	@echo "... AppMatch/AppMatch/ParserTextEntry.o"
	@echo "... AppMatch/AppMatch/ParserTextEntry.i"
	@echo "... AppMatch/AppMatch/ParserTextEntry.s"
	@echo "... AppMatch/AppMatch/Parser_A.o"
	@echo "... AppMatch/AppMatch/Parser_A.i"
	@echo "... AppMatch/AppMatch/Parser_A.s"
	@echo "... AppMatch/AppMatch/Parser_Decide.o"
	@echo "... AppMatch/AppMatch/Parser_Decide.i"
	@echo "... AppMatch/AppMatch/Parser_Decide.s"
	@echo "... AppMatch/AppMatch/Parser_expression_match.o"
	@echo "... AppMatch/AppMatch/Parser_expression_match.i"
	@echo "... AppMatch/AppMatch/Parser_expression_match.s"
	@echo "... AppMatch/AppMatch/QueryItem.o"
	@echo "... AppMatch/AppMatch/QueryItem.i"
	@echo "... AppMatch/AppMatch/QueryItem.s"
	@echo "... AppMatch/AppMatch/RepresentationFunctions.o"
	@echo "... AppMatch/AppMatch/RepresentationFunctions.i"
	@echo "... AppMatch/AppMatch/RepresentationFunctions.s"
	@echo "... AppMatch/AppMatch/StaticDispatchFunctions.o"
	@echo "... AppMatch/AppMatch/StaticDispatchFunctions.i"
	@echo "... AppMatch/AppMatch/StaticDispatchFunctions.s"
	@echo "... AppMatch/AppMatch/stdafx.o"
	@echo "... AppMatch/AppMatch/stdafx.i"
	@echo "... AppMatch/AppMatch/stdafx.s"
	@echo "... AppMatch/AppMatch/testeLista.o"
	@echo "... AppMatch/AppMatch/testeLista.i"
	@echo "... AppMatch/AppMatch/testeLista.s"
	@echo "... AppMatch/AppMatch/testesParser.o"
	@echo "... AppMatch/AppMatch/testesParser.i"
	@echo "... AppMatch/AppMatch/testesParser.s"
	@echo "... AppMatch/AppMatch/testes_1.o"
	@echo "... AppMatch/AppMatch/testes_1.i"
	@echo "... AppMatch/AppMatch/testes_1.s"
	@echo "... AppMatch/AppMatch/testes_2.o"
	@echo "... AppMatch/AppMatch/testes_2.i"
	@echo "... AppMatch/AppMatch/testes_2.s"
	@echo "... AppMatch/AppMatch/testes_decide.o"
	@echo "... AppMatch/AppMatch/testes_decide.i"
	@echo "... AppMatch/AppMatch/testes_decide.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

