# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/astrowar/git/CMatchIteractiveFic

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/astrowar/git/CMatchIteractiveFic

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/astrowar/git/CMatchIteractiveFic/CMakeFiles /Users/astrowar/git/CMatchIteractiveFic/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/astrowar/git/CMatchIteractiveFic/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named apx

# Build rule for target.
apx: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 apx
.PHONY : apx

# fast build rule for target.
apx/fast:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/build
.PHONY : apx/fast

AppMatch/AppMatch/AssertationDefaultValue.o: AppMatch/AppMatch/AssertationDefaultValue.cpp.o

.PHONY : AppMatch/AppMatch/AssertationDefaultValue.o

# target to build an object file
AppMatch/AppMatch/AssertationDefaultValue.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/AssertationDefaultValue.cpp.o
.PHONY : AppMatch/AppMatch/AssertationDefaultValue.cpp.o

AppMatch/AppMatch/AssertationDefaultValue.i: AppMatch/AppMatch/AssertationDefaultValue.cpp.i

.PHONY : AppMatch/AppMatch/AssertationDefaultValue.i

# target to preprocess a source file
AppMatch/AppMatch/AssertationDefaultValue.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/AssertationDefaultValue.cpp.i
.PHONY : AppMatch/AppMatch/AssertationDefaultValue.cpp.i

AppMatch/AppMatch/AssertationDefaultValue.s: AppMatch/AppMatch/AssertationDefaultValue.cpp.s

.PHONY : AppMatch/AppMatch/AssertationDefaultValue.s

# target to generate assembly for a file
AppMatch/AppMatch/AssertationDefaultValue.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/AssertationDefaultValue.cpp.s
.PHONY : AppMatch/AppMatch/AssertationDefaultValue.cpp.s

AppMatch/AppMatch/AssertationEngine.o: AppMatch/AppMatch/AssertationEngine.cpp.o

.PHONY : AppMatch/AppMatch/AssertationEngine.o

# target to build an object file
AppMatch/AppMatch/AssertationEngine.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/AssertationEngine.cpp.o
.PHONY : AppMatch/AppMatch/AssertationEngine.cpp.o

AppMatch/AppMatch/AssertationEngine.i: AppMatch/AppMatch/AssertationEngine.cpp.i

.PHONY : AppMatch/AppMatch/AssertationEngine.i

# target to preprocess a source file
AppMatch/AppMatch/AssertationEngine.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/AssertationEngine.cpp.i
.PHONY : AppMatch/AppMatch/AssertationEngine.cpp.i

AppMatch/AppMatch/AssertationEngine.s: AppMatch/AppMatch/AssertationEngine.cpp.s

.PHONY : AppMatch/AppMatch/AssertationEngine.s

# target to generate assembly for a file
AppMatch/AppMatch/AssertationEngine.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/AssertationEngine.cpp.s
.PHONY : AppMatch/AppMatch/AssertationEngine.cpp.s

AppMatch/AppMatch/AssertationVerbRelation.o: AppMatch/AppMatch/AssertationVerbRelation.cpp.o

.PHONY : AppMatch/AppMatch/AssertationVerbRelation.o

# target to build an object file
AppMatch/AppMatch/AssertationVerbRelation.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/AssertationVerbRelation.cpp.o
.PHONY : AppMatch/AppMatch/AssertationVerbRelation.cpp.o

AppMatch/AppMatch/AssertationVerbRelation.i: AppMatch/AppMatch/AssertationVerbRelation.cpp.i

.PHONY : AppMatch/AppMatch/AssertationVerbRelation.i

# target to preprocess a source file
AppMatch/AppMatch/AssertationVerbRelation.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/AssertationVerbRelation.cpp.i
.PHONY : AppMatch/AppMatch/AssertationVerbRelation.cpp.i

AppMatch/AppMatch/AssertationVerbRelation.s: AppMatch/AppMatch/AssertationVerbRelation.cpp.s

.PHONY : AppMatch/AppMatch/AssertationVerbRelation.s

# target to generate assembly for a file
AppMatch/AppMatch/AssertationVerbRelation.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/AssertationVerbRelation.cpp.s
.PHONY : AppMatch/AppMatch/AssertationVerbRelation.cpp.s

AppMatch/AppMatch/AssertionValues.o: AppMatch/AppMatch/AssertionValues.cpp.o

.PHONY : AppMatch/AppMatch/AssertionValues.o

# target to build an object file
AppMatch/AppMatch/AssertionValues.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/AssertionValues.cpp.o
.PHONY : AppMatch/AppMatch/AssertionValues.cpp.o

AppMatch/AppMatch/AssertionValues.i: AppMatch/AppMatch/AssertionValues.cpp.i

.PHONY : AppMatch/AppMatch/AssertionValues.i

# target to preprocess a source file
AppMatch/AppMatch/AssertionValues.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/AssertionValues.cpp.i
.PHONY : AppMatch/AppMatch/AssertionValues.cpp.i

AppMatch/AppMatch/AssertionValues.s: AppMatch/AppMatch/AssertionValues.cpp.s

.PHONY : AppMatch/AppMatch/AssertionValues.s

# target to generate assembly for a file
AppMatch/AppMatch/AssertionValues.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/AssertionValues.cpp.s
.PHONY : AppMatch/AppMatch/AssertionValues.cpp.s

AppMatch/AppMatch/BlockInstance.o: AppMatch/AppMatch/BlockInstance.cpp.o

.PHONY : AppMatch/AppMatch/BlockInstance.o

# target to build an object file
AppMatch/AppMatch/BlockInstance.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/BlockInstance.cpp.o
.PHONY : AppMatch/AppMatch/BlockInstance.cpp.o

AppMatch/AppMatch/BlockInstance.i: AppMatch/AppMatch/BlockInstance.cpp.i

.PHONY : AppMatch/AppMatch/BlockInstance.i

# target to preprocess a source file
AppMatch/AppMatch/BlockInstance.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/BlockInstance.cpp.i
.PHONY : AppMatch/AppMatch/BlockInstance.cpp.i

AppMatch/AppMatch/BlockInstance.s: AppMatch/AppMatch/BlockInstance.cpp.s

.PHONY : AppMatch/AppMatch/BlockInstance.s

# target to generate assembly for a file
AppMatch/AppMatch/BlockInstance.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/BlockInstance.cpp.s
.PHONY : AppMatch/AppMatch/BlockInstance.cpp.s

AppMatch/AppMatch/BlockInterpreter.o: AppMatch/AppMatch/BlockInterpreter.cpp.o

.PHONY : AppMatch/AppMatch/BlockInterpreter.o

# target to build an object file
AppMatch/AppMatch/BlockInterpreter.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/BlockInterpreter.cpp.o
.PHONY : AppMatch/AppMatch/BlockInterpreter.cpp.o

AppMatch/AppMatch/BlockInterpreter.i: AppMatch/AppMatch/BlockInterpreter.cpp.i

.PHONY : AppMatch/AppMatch/BlockInterpreter.i

# target to preprocess a source file
AppMatch/AppMatch/BlockInterpreter.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/BlockInterpreter.cpp.i
.PHONY : AppMatch/AppMatch/BlockInterpreter.cpp.i

AppMatch/AppMatch/BlockInterpreter.s: AppMatch/AppMatch/BlockInterpreter.cpp.s

.PHONY : AppMatch/AppMatch/BlockInterpreter.s

# target to generate assembly for a file
AppMatch/AppMatch/BlockInterpreter.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/BlockInterpreter.cpp.s
.PHONY : AppMatch/AppMatch/BlockInterpreter.cpp.s

AppMatch/AppMatch/BlockisSame.o: AppMatch/AppMatch/BlockisSame.cpp.o

.PHONY : AppMatch/AppMatch/BlockisSame.o

# target to build an object file
AppMatch/AppMatch/BlockisSame.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/BlockisSame.cpp.o
.PHONY : AppMatch/AppMatch/BlockisSame.cpp.o

AppMatch/AppMatch/BlockisSame.i: AppMatch/AppMatch/BlockisSame.cpp.i

.PHONY : AppMatch/AppMatch/BlockisSame.i

# target to preprocess a source file
AppMatch/AppMatch/BlockisSame.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/BlockisSame.cpp.i
.PHONY : AppMatch/AppMatch/BlockisSame.cpp.i

AppMatch/AppMatch/BlockisSame.s: AppMatch/AppMatch/BlockisSame.cpp.s

.PHONY : AppMatch/AppMatch/BlockisSame.s

# target to generate assembly for a file
AppMatch/AppMatch/BlockisSame.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/BlockisSame.cpp.s
.PHONY : AppMatch/AppMatch/BlockisSame.cpp.s

AppMatch/AppMatch/CBase.o: AppMatch/AppMatch/CBase.cpp.o

.PHONY : AppMatch/AppMatch/CBase.o

# target to build an object file
AppMatch/AppMatch/CBase.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CBase.cpp.o
.PHONY : AppMatch/AppMatch/CBase.cpp.o

AppMatch/AppMatch/CBase.i: AppMatch/AppMatch/CBase.cpp.i

.PHONY : AppMatch/AppMatch/CBase.i

# target to preprocess a source file
AppMatch/AppMatch/CBase.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CBase.cpp.i
.PHONY : AppMatch/AppMatch/CBase.cpp.i

AppMatch/AppMatch/CBase.s: AppMatch/AppMatch/CBase.cpp.s

.PHONY : AppMatch/AppMatch/CBase.s

# target to generate assembly for a file
AppMatch/AppMatch/CBase.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CBase.cpp.s
.PHONY : AppMatch/AppMatch/CBase.cpp.s

AppMatch/AppMatch/CBlockDumpValues.o: AppMatch/AppMatch/CBlockDumpValues.cpp.o

.PHONY : AppMatch/AppMatch/CBlockDumpValues.o

# target to build an object file
AppMatch/AppMatch/CBlockDumpValues.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CBlockDumpValues.cpp.o
.PHONY : AppMatch/AppMatch/CBlockDumpValues.cpp.o

AppMatch/AppMatch/CBlockDumpValues.i: AppMatch/AppMatch/CBlockDumpValues.cpp.i

.PHONY : AppMatch/AppMatch/CBlockDumpValues.i

# target to preprocess a source file
AppMatch/AppMatch/CBlockDumpValues.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CBlockDumpValues.cpp.i
.PHONY : AppMatch/AppMatch/CBlockDumpValues.cpp.i

AppMatch/AppMatch/CBlockDumpValues.s: AppMatch/AppMatch/CBlockDumpValues.cpp.s

.PHONY : AppMatch/AppMatch/CBlockDumpValues.s

# target to generate assembly for a file
AppMatch/AppMatch/CBlockDumpValues.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CBlockDumpValues.cpp.s
.PHONY : AppMatch/AppMatch/CBlockDumpValues.cpp.s

AppMatch/AppMatch/CBlockInterpreterDecideBody.o: AppMatch/AppMatch/CBlockInterpreterDecideBody.cpp.o

.PHONY : AppMatch/AppMatch/CBlockInterpreterDecideBody.o

# target to build an object file
AppMatch/AppMatch/CBlockInterpreterDecideBody.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CBlockInterpreterDecideBody.cpp.o
.PHONY : AppMatch/AppMatch/CBlockInterpreterDecideBody.cpp.o

AppMatch/AppMatch/CBlockInterpreterDecideBody.i: AppMatch/AppMatch/CBlockInterpreterDecideBody.cpp.i

.PHONY : AppMatch/AppMatch/CBlockInterpreterDecideBody.i

# target to preprocess a source file
AppMatch/AppMatch/CBlockInterpreterDecideBody.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CBlockInterpreterDecideBody.cpp.i
.PHONY : AppMatch/AppMatch/CBlockInterpreterDecideBody.cpp.i

AppMatch/AppMatch/CBlockInterpreterDecideBody.s: AppMatch/AppMatch/CBlockInterpreterDecideBody.cpp.s

.PHONY : AppMatch/AppMatch/CBlockInterpreterDecideBody.s

# target to generate assembly for a file
AppMatch/AppMatch/CBlockInterpreterDecideBody.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CBlockInterpreterDecideBody.cpp.s
.PHONY : AppMatch/AppMatch/CBlockInterpreterDecideBody.cpp.s

AppMatch/AppMatch/CBlockInterpreterRuntime.o: AppMatch/AppMatch/CBlockInterpreterRuntime.cpp.o

.PHONY : AppMatch/AppMatch/CBlockInterpreterRuntime.o

# target to build an object file
AppMatch/AppMatch/CBlockInterpreterRuntime.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CBlockInterpreterRuntime.cpp.o
.PHONY : AppMatch/AppMatch/CBlockInterpreterRuntime.cpp.o

AppMatch/AppMatch/CBlockInterpreterRuntime.i: AppMatch/AppMatch/CBlockInterpreterRuntime.cpp.i

.PHONY : AppMatch/AppMatch/CBlockInterpreterRuntime.i

# target to preprocess a source file
AppMatch/AppMatch/CBlockInterpreterRuntime.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CBlockInterpreterRuntime.cpp.i
.PHONY : AppMatch/AppMatch/CBlockInterpreterRuntime.cpp.i

AppMatch/AppMatch/CBlockInterpreterRuntime.s: AppMatch/AppMatch/CBlockInterpreterRuntime.cpp.s

.PHONY : AppMatch/AppMatch/CBlockInterpreterRuntime.s

# target to generate assembly for a file
AppMatch/AppMatch/CBlockInterpreterRuntime.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CBlockInterpreterRuntime.cpp.s
.PHONY : AppMatch/AppMatch/CBlockInterpreterRuntime.cpp.s

AppMatch/AppMatch/CBlockInterpreter_Verb_En.o: AppMatch/AppMatch/CBlockInterpreter_Verb_En.cpp.o

.PHONY : AppMatch/AppMatch/CBlockInterpreter_Verb_En.o

# target to build an object file
AppMatch/AppMatch/CBlockInterpreter_Verb_En.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CBlockInterpreter_Verb_En.cpp.o
.PHONY : AppMatch/AppMatch/CBlockInterpreter_Verb_En.cpp.o

AppMatch/AppMatch/CBlockInterpreter_Verb_En.i: AppMatch/AppMatch/CBlockInterpreter_Verb_En.cpp.i

.PHONY : AppMatch/AppMatch/CBlockInterpreter_Verb_En.i

# target to preprocess a source file
AppMatch/AppMatch/CBlockInterpreter_Verb_En.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CBlockInterpreter_Verb_En.cpp.i
.PHONY : AppMatch/AppMatch/CBlockInterpreter_Verb_En.cpp.i

AppMatch/AppMatch/CBlockInterpreter_Verb_En.s: AppMatch/AppMatch/CBlockInterpreter_Verb_En.cpp.s

.PHONY : AppMatch/AppMatch/CBlockInterpreter_Verb_En.s

# target to generate assembly for a file
AppMatch/AppMatch/CBlockInterpreter_Verb_En.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CBlockInterpreter_Verb_En.cpp.s
.PHONY : AppMatch/AppMatch/CBlockInterpreter_Verb_En.cpp.s

AppMatch/AppMatch/CBlockSerialize.o: AppMatch/AppMatch/CBlockSerialize.cpp.o

.PHONY : AppMatch/AppMatch/CBlockSerialize.o

# target to build an object file
AppMatch/AppMatch/CBlockSerialize.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CBlockSerialize.cpp.o
.PHONY : AppMatch/AppMatch/CBlockSerialize.cpp.o

AppMatch/AppMatch/CBlockSerialize.i: AppMatch/AppMatch/CBlockSerialize.cpp.i

.PHONY : AppMatch/AppMatch/CBlockSerialize.i

# target to preprocess a source file
AppMatch/AppMatch/CBlockSerialize.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CBlockSerialize.cpp.i
.PHONY : AppMatch/AppMatch/CBlockSerialize.cpp.i

AppMatch/AppMatch/CBlockSerialize.s: AppMatch/AppMatch/CBlockSerialize.cpp.s

.PHONY : AppMatch/AppMatch/CBlockSerialize.s

# target to generate assembly for a file
AppMatch/AppMatch/CBlockSerialize.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CBlockSerialize.cpp.s
.PHONY : AppMatch/AppMatch/CBlockSerialize.cpp.s

AppMatch/AppMatch/CDataMananger.o: AppMatch/AppMatch/CDataMananger.cpp.o

.PHONY : AppMatch/AppMatch/CDataMananger.o

# target to build an object file
AppMatch/AppMatch/CDataMananger.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CDataMananger.cpp.o
.PHONY : AppMatch/AppMatch/CDataMananger.cpp.o

AppMatch/AppMatch/CDataMananger.i: AppMatch/AppMatch/CDataMananger.cpp.i

.PHONY : AppMatch/AppMatch/CDataMananger.i

# target to preprocess a source file
AppMatch/AppMatch/CDataMananger.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CDataMananger.cpp.i
.PHONY : AppMatch/AppMatch/CDataMananger.cpp.i

AppMatch/AppMatch/CDataMananger.s: AppMatch/AppMatch/CDataMananger.cpp.s

.PHONY : AppMatch/AppMatch/CDataMananger.s

# target to generate assembly for a file
AppMatch/AppMatch/CDataMananger.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CDataMananger.cpp.s
.PHONY : AppMatch/AppMatch/CDataMananger.cpp.s

AppMatch/AppMatch/CInterpreterEvaluate.o: AppMatch/AppMatch/CInterpreterEvaluate.cpp.o

.PHONY : AppMatch/AppMatch/CInterpreterEvaluate.o

# target to build an object file
AppMatch/AppMatch/CInterpreterEvaluate.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CInterpreterEvaluate.cpp.o
.PHONY : AppMatch/AppMatch/CInterpreterEvaluate.cpp.o

AppMatch/AppMatch/CInterpreterEvaluate.i: AppMatch/AppMatch/CInterpreterEvaluate.cpp.i

.PHONY : AppMatch/AppMatch/CInterpreterEvaluate.i

# target to preprocess a source file
AppMatch/AppMatch/CInterpreterEvaluate.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CInterpreterEvaluate.cpp.i
.PHONY : AppMatch/AppMatch/CInterpreterEvaluate.cpp.i

AppMatch/AppMatch/CInterpreterEvaluate.s: AppMatch/AppMatch/CInterpreterEvaluate.cpp.s

.PHONY : AppMatch/AppMatch/CInterpreterEvaluate.s

# target to generate assembly for a file
AppMatch/AppMatch/CInterpreterEvaluate.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CInterpreterEvaluate.cpp.s
.PHONY : AppMatch/AppMatch/CInterpreterEvaluate.cpp.s

AppMatch/AppMatch/CInterpreterKindTree.o: AppMatch/AppMatch/CInterpreterKindTree.cpp.o

.PHONY : AppMatch/AppMatch/CInterpreterKindTree.o

# target to build an object file
AppMatch/AppMatch/CInterpreterKindTree.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CInterpreterKindTree.cpp.o
.PHONY : AppMatch/AppMatch/CInterpreterKindTree.cpp.o

AppMatch/AppMatch/CInterpreterKindTree.i: AppMatch/AppMatch/CInterpreterKindTree.cpp.i

.PHONY : AppMatch/AppMatch/CInterpreterKindTree.i

# target to preprocess a source file
AppMatch/AppMatch/CInterpreterKindTree.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CInterpreterKindTree.cpp.i
.PHONY : AppMatch/AppMatch/CInterpreterKindTree.cpp.i

AppMatch/AppMatch/CInterpreterKindTree.s: AppMatch/AppMatch/CInterpreterKindTree.cpp.s

.PHONY : AppMatch/AppMatch/CInterpreterKindTree.s

# target to generate assembly for a file
AppMatch/AppMatch/CInterpreterKindTree.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CInterpreterKindTree.cpp.s
.PHONY : AppMatch/AppMatch/CInterpreterKindTree.cpp.s

AppMatch/AppMatch/CInterpreterRelation.o: AppMatch/AppMatch/CInterpreterRelation.cpp.o

.PHONY : AppMatch/AppMatch/CInterpreterRelation.o

# target to build an object file
AppMatch/AppMatch/CInterpreterRelation.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CInterpreterRelation.cpp.o
.PHONY : AppMatch/AppMatch/CInterpreterRelation.cpp.o

AppMatch/AppMatch/CInterpreterRelation.i: AppMatch/AppMatch/CInterpreterRelation.cpp.i

.PHONY : AppMatch/AppMatch/CInterpreterRelation.i

# target to preprocess a source file
AppMatch/AppMatch/CInterpreterRelation.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CInterpreterRelation.cpp.i
.PHONY : AppMatch/AppMatch/CInterpreterRelation.cpp.i

AppMatch/AppMatch/CInterpreterRelation.s: AppMatch/AppMatch/CInterpreterRelation.cpp.s

.PHONY : AppMatch/AppMatch/CInterpreterRelation.s

# target to generate assembly for a file
AppMatch/AppMatch/CInterpreterRelation.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CInterpreterRelation.cpp.s
.PHONY : AppMatch/AppMatch/CInterpreterRelation.cpp.s

AppMatch/AppMatch/CInterpreterResolve.o: AppMatch/AppMatch/CInterpreterResolve.cpp.o

.PHONY : AppMatch/AppMatch/CInterpreterResolve.o

# target to build an object file
AppMatch/AppMatch/CInterpreterResolve.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CInterpreterResolve.cpp.o
.PHONY : AppMatch/AppMatch/CInterpreterResolve.cpp.o

AppMatch/AppMatch/CInterpreterResolve.i: AppMatch/AppMatch/CInterpreterResolve.cpp.i

.PHONY : AppMatch/AppMatch/CInterpreterResolve.i

# target to preprocess a source file
AppMatch/AppMatch/CInterpreterResolve.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CInterpreterResolve.cpp.i
.PHONY : AppMatch/AppMatch/CInterpreterResolve.cpp.i

AppMatch/AppMatch/CInterpreterResolve.s: AppMatch/AppMatch/CInterpreterResolve.cpp.s

.PHONY : AppMatch/AppMatch/CInterpreterResolve.s

# target to generate assembly for a file
AppMatch/AppMatch/CInterpreterResolve.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CInterpreterResolve.cpp.s
.PHONY : AppMatch/AppMatch/CInterpreterResolve.cpp.s

AppMatch/AppMatch/CInterpreterResolveMatchSeletor.o: AppMatch/AppMatch/CInterpreterResolveMatchSeletor.cpp.o

.PHONY : AppMatch/AppMatch/CInterpreterResolveMatchSeletor.o

# target to build an object file
AppMatch/AppMatch/CInterpreterResolveMatchSeletor.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CInterpreterResolveMatchSeletor.cpp.o
.PHONY : AppMatch/AppMatch/CInterpreterResolveMatchSeletor.cpp.o

AppMatch/AppMatch/CInterpreterResolveMatchSeletor.i: AppMatch/AppMatch/CInterpreterResolveMatchSeletor.cpp.i

.PHONY : AppMatch/AppMatch/CInterpreterResolveMatchSeletor.i

# target to preprocess a source file
AppMatch/AppMatch/CInterpreterResolveMatchSeletor.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CInterpreterResolveMatchSeletor.cpp.i
.PHONY : AppMatch/AppMatch/CInterpreterResolveMatchSeletor.cpp.i

AppMatch/AppMatch/CInterpreterResolveMatchSeletor.s: AppMatch/AppMatch/CInterpreterResolveMatchSeletor.cpp.s

.PHONY : AppMatch/AppMatch/CInterpreterResolveMatchSeletor.s

# target to generate assembly for a file
AppMatch/AppMatch/CInterpreterResolveMatchSeletor.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CInterpreterResolveMatchSeletor.cpp.s
.PHONY : AppMatch/AppMatch/CInterpreterResolveMatchSeletor.cpp.s

AppMatch/AppMatch/CMatch.o: AppMatch/AppMatch/CMatch.cpp.o

.PHONY : AppMatch/AppMatch/CMatch.o

# target to build an object file
AppMatch/AppMatch/CMatch.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CMatch.cpp.o
.PHONY : AppMatch/AppMatch/CMatch.cpp.o

AppMatch/AppMatch/CMatch.i: AppMatch/AppMatch/CMatch.cpp.i

.PHONY : AppMatch/AppMatch/CMatch.i

# target to preprocess a source file
AppMatch/AppMatch/CMatch.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CMatch.cpp.i
.PHONY : AppMatch/AppMatch/CMatch.cpp.i

AppMatch/AppMatch/CMatch.s: AppMatch/AppMatch/CMatch.cpp.s

.PHONY : AppMatch/AppMatch/CMatch.s

# target to generate assembly for a file
AppMatch/AppMatch/CMatch.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CMatch.cpp.s
.PHONY : AppMatch/AppMatch/CMatch.cpp.s

AppMatch/AppMatch/CMatchCombinatoria.o: AppMatch/AppMatch/CMatchCombinatoria.cpp.o

.PHONY : AppMatch/AppMatch/CMatchCombinatoria.o

# target to build an object file
AppMatch/AppMatch/CMatchCombinatoria.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CMatchCombinatoria.cpp.o
.PHONY : AppMatch/AppMatch/CMatchCombinatoria.cpp.o

AppMatch/AppMatch/CMatchCombinatoria.i: AppMatch/AppMatch/CMatchCombinatoria.cpp.i

.PHONY : AppMatch/AppMatch/CMatchCombinatoria.i

# target to preprocess a source file
AppMatch/AppMatch/CMatchCombinatoria.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CMatchCombinatoria.cpp.i
.PHONY : AppMatch/AppMatch/CMatchCombinatoria.cpp.i

AppMatch/AppMatch/CMatchCombinatoria.s: AppMatch/AppMatch/CMatchCombinatoria.cpp.s

.PHONY : AppMatch/AppMatch/CMatchCombinatoria.s

# target to generate assembly for a file
AppMatch/AppMatch/CMatchCombinatoria.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CMatchCombinatoria.cpp.s
.PHONY : AppMatch/AppMatch/CMatchCombinatoria.cpp.s

AppMatch/AppMatch/CMatchListValid.o: AppMatch/AppMatch/CMatchListValid.cpp.o

.PHONY : AppMatch/AppMatch/CMatchListValid.o

# target to build an object file
AppMatch/AppMatch/CMatchListValid.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CMatchListValid.cpp.o
.PHONY : AppMatch/AppMatch/CMatchListValid.cpp.o

AppMatch/AppMatch/CMatchListValid.i: AppMatch/AppMatch/CMatchListValid.cpp.i

.PHONY : AppMatch/AppMatch/CMatchListValid.i

# target to preprocess a source file
AppMatch/AppMatch/CMatchListValid.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CMatchListValid.cpp.i
.PHONY : AppMatch/AppMatch/CMatchListValid.cpp.i

AppMatch/AppMatch/CMatchListValid.s: AppMatch/AppMatch/CMatchListValid.cpp.s

.PHONY : AppMatch/AppMatch/CMatchListValid.s

# target to generate assembly for a file
AppMatch/AppMatch/CMatchListValid.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CMatchListValid.cpp.s
.PHONY : AppMatch/AppMatch/CMatchListValid.cpp.s

AppMatch/AppMatch/CParseAux.o: AppMatch/AppMatch/CParseAux.cpp.o

.PHONY : AppMatch/AppMatch/CParseAux.o

# target to build an object file
AppMatch/AppMatch/CParseAux.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CParseAux.cpp.o
.PHONY : AppMatch/AppMatch/CParseAux.cpp.o

AppMatch/AppMatch/CParseAux.i: AppMatch/AppMatch/CParseAux.cpp.i

.PHONY : AppMatch/AppMatch/CParseAux.i

# target to preprocess a source file
AppMatch/AppMatch/CParseAux.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CParseAux.cpp.i
.PHONY : AppMatch/AppMatch/CParseAux.cpp.i

AppMatch/AppMatch/CParseAux.s: AppMatch/AppMatch/CParseAux.cpp.s

.PHONY : AppMatch/AppMatch/CParseAux.s

# target to generate assembly for a file
AppMatch/AppMatch/CParseAux.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CParseAux.cpp.s
.PHONY : AppMatch/AppMatch/CParseAux.cpp.s

AppMatch/AppMatch/CResultMatch.o: AppMatch/AppMatch/CResultMatch.cpp.o

.PHONY : AppMatch/AppMatch/CResultMatch.o

# target to build an object file
AppMatch/AppMatch/CResultMatch.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CResultMatch.cpp.o
.PHONY : AppMatch/AppMatch/CResultMatch.cpp.o

AppMatch/AppMatch/CResultMatch.i: AppMatch/AppMatch/CResultMatch.cpp.i

.PHONY : AppMatch/AppMatch/CResultMatch.i

# target to preprocess a source file
AppMatch/AppMatch/CResultMatch.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CResultMatch.cpp.i
.PHONY : AppMatch/AppMatch/CResultMatch.cpp.i

AppMatch/AppMatch/CResultMatch.s: AppMatch/AppMatch/CResultMatch.cpp.s

.PHONY : AppMatch/AppMatch/CResultMatch.s

# target to generate assembly for a file
AppMatch/AppMatch/CResultMatch.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CResultMatch.cpp.s
.PHONY : AppMatch/AppMatch/CResultMatch.cpp.s

AppMatch/AppMatch/CVariableGlobals.o: AppMatch/AppMatch/CVariableGlobals.cpp.o

.PHONY : AppMatch/AppMatch/CVariableGlobals.o

# target to build an object file
AppMatch/AppMatch/CVariableGlobals.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CVariableGlobals.cpp.o
.PHONY : AppMatch/AppMatch/CVariableGlobals.cpp.o

AppMatch/AppMatch/CVariableGlobals.i: AppMatch/AppMatch/CVariableGlobals.cpp.i

.PHONY : AppMatch/AppMatch/CVariableGlobals.i

# target to preprocess a source file
AppMatch/AppMatch/CVariableGlobals.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CVariableGlobals.cpp.i
.PHONY : AppMatch/AppMatch/CVariableGlobals.cpp.i

AppMatch/AppMatch/CVariableGlobals.s: AppMatch/AppMatch/CVariableGlobals.cpp.s

.PHONY : AppMatch/AppMatch/CVariableGlobals.s

# target to generate assembly for a file
AppMatch/AppMatch/CVariableGlobals.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CVariableGlobals.cpp.s
.PHONY : AppMatch/AppMatch/CVariableGlobals.cpp.s

AppMatch/AppMatch/CreateInstanceInterpreter.o: AppMatch/AppMatch/CreateInstanceInterpreter.cpp.o

.PHONY : AppMatch/AppMatch/CreateInstanceInterpreter.o

# target to build an object file
AppMatch/AppMatch/CreateInstanceInterpreter.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CreateInstanceInterpreter.cpp.o
.PHONY : AppMatch/AppMatch/CreateInstanceInterpreter.cpp.o

AppMatch/AppMatch/CreateInstanceInterpreter.i: AppMatch/AppMatch/CreateInstanceInterpreter.cpp.i

.PHONY : AppMatch/AppMatch/CreateInstanceInterpreter.i

# target to preprocess a source file
AppMatch/AppMatch/CreateInstanceInterpreter.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CreateInstanceInterpreter.cpp.i
.PHONY : AppMatch/AppMatch/CreateInstanceInterpreter.cpp.i

AppMatch/AppMatch/CreateInstanceInterpreter.s: AppMatch/AppMatch/CreateInstanceInterpreter.cpp.s

.PHONY : AppMatch/AppMatch/CreateInstanceInterpreter.s

# target to generate assembly for a file
AppMatch/AppMatch/CreateInstanceInterpreter.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/CreateInstanceInterpreter.cpp.s
.PHONY : AppMatch/AppMatch/CreateInstanceInterpreter.cpp.s

AppMatch/AppMatch/InterpExecute.o: AppMatch/AppMatch/InterpExecute.cpp.o

.PHONY : AppMatch/AppMatch/InterpExecute.o

# target to build an object file
AppMatch/AppMatch/InterpExecute.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/InterpExecute.cpp.o
.PHONY : AppMatch/AppMatch/InterpExecute.cpp.o

AppMatch/AppMatch/InterpExecute.i: AppMatch/AppMatch/InterpExecute.cpp.i

.PHONY : AppMatch/AppMatch/InterpExecute.i

# target to preprocess a source file
AppMatch/AppMatch/InterpExecute.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/InterpExecute.cpp.i
.PHONY : AppMatch/AppMatch/InterpExecute.cpp.i

AppMatch/AppMatch/InterpExecute.s: AppMatch/AppMatch/InterpExecute.cpp.s

.PHONY : AppMatch/AppMatch/InterpExecute.s

# target to generate assembly for a file
AppMatch/AppMatch/InterpExecute.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/InterpExecute.cpp.s
.PHONY : AppMatch/AppMatch/InterpExecute.cpp.s

AppMatch/AppMatch/InterpFunctionsCallcpp.o: AppMatch/AppMatch/InterpFunctionsCallcpp.cpp.o

.PHONY : AppMatch/AppMatch/InterpFunctionsCallcpp.o

# target to build an object file
AppMatch/AppMatch/InterpFunctionsCallcpp.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/InterpFunctionsCallcpp.cpp.o
.PHONY : AppMatch/AppMatch/InterpFunctionsCallcpp.cpp.o

AppMatch/AppMatch/InterpFunctionsCallcpp.i: AppMatch/AppMatch/InterpFunctionsCallcpp.cpp.i

.PHONY : AppMatch/AppMatch/InterpFunctionsCallcpp.i

# target to preprocess a source file
AppMatch/AppMatch/InterpFunctionsCallcpp.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/InterpFunctionsCallcpp.cpp.i
.PHONY : AppMatch/AppMatch/InterpFunctionsCallcpp.cpp.i

AppMatch/AppMatch/InterpFunctionsCallcpp.s: AppMatch/AppMatch/InterpFunctionsCallcpp.cpp.s

.PHONY : AppMatch/AppMatch/InterpFunctionsCallcpp.s

# target to generate assembly for a file
AppMatch/AppMatch/InterpFunctionsCallcpp.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/InterpFunctionsCallcpp.cpp.s
.PHONY : AppMatch/AppMatch/InterpFunctionsCallcpp.cpp.s

AppMatch/AppMatch/InterpreterListedFunctions.o: AppMatch/AppMatch/InterpreterListedFunctions.cpp.o

.PHONY : AppMatch/AppMatch/InterpreterListedFunctions.o

# target to build an object file
AppMatch/AppMatch/InterpreterListedFunctions.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/InterpreterListedFunctions.cpp.o
.PHONY : AppMatch/AppMatch/InterpreterListedFunctions.cpp.o

AppMatch/AppMatch/InterpreterListedFunctions.i: AppMatch/AppMatch/InterpreterListedFunctions.cpp.i

.PHONY : AppMatch/AppMatch/InterpreterListedFunctions.i

# target to preprocess a source file
AppMatch/AppMatch/InterpreterListedFunctions.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/InterpreterListedFunctions.cpp.i
.PHONY : AppMatch/AppMatch/InterpreterListedFunctions.cpp.i

AppMatch/AppMatch/InterpreterListedFunctions.s: AppMatch/AppMatch/InterpreterListedFunctions.cpp.s

.PHONY : AppMatch/AppMatch/InterpreterListedFunctions.s

# target to generate assembly for a file
AppMatch/AppMatch/InterpreterListedFunctions.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/InterpreterListedFunctions.cpp.s
.PHONY : AppMatch/AppMatch/InterpreterListedFunctions.cpp.s

AppMatch/AppMatch/InterpreterMatch.o: AppMatch/AppMatch/InterpreterMatch.cpp.o

.PHONY : AppMatch/AppMatch/InterpreterMatch.o

# target to build an object file
AppMatch/AppMatch/InterpreterMatch.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/InterpreterMatch.cpp.o
.PHONY : AppMatch/AppMatch/InterpreterMatch.cpp.o

AppMatch/AppMatch/InterpreterMatch.i: AppMatch/AppMatch/InterpreterMatch.cpp.i

.PHONY : AppMatch/AppMatch/InterpreterMatch.i

# target to preprocess a source file
AppMatch/AppMatch/InterpreterMatch.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/InterpreterMatch.cpp.i
.PHONY : AppMatch/AppMatch/InterpreterMatch.cpp.i

AppMatch/AppMatch/InterpreterMatch.s: AppMatch/AppMatch/InterpreterMatch.cpp.s

.PHONY : AppMatch/AppMatch/InterpreterMatch.s

# target to generate assembly for a file
AppMatch/AppMatch/InterpreterMatch.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/InterpreterMatch.cpp.s
.PHONY : AppMatch/AppMatch/InterpreterMatch.cpp.s

AppMatch/AppMatch/InterpreterQuery.o: AppMatch/AppMatch/InterpreterQuery.cpp.o

.PHONY : AppMatch/AppMatch/InterpreterQuery.o

# target to build an object file
AppMatch/AppMatch/InterpreterQuery.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/InterpreterQuery.cpp.o
.PHONY : AppMatch/AppMatch/InterpreterQuery.cpp.o

AppMatch/AppMatch/InterpreterQuery.i: AppMatch/AppMatch/InterpreterQuery.cpp.i

.PHONY : AppMatch/AppMatch/InterpreterQuery.i

# target to preprocess a source file
AppMatch/AppMatch/InterpreterQuery.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/InterpreterQuery.cpp.i
.PHONY : AppMatch/AppMatch/InterpreterQuery.cpp.i

AppMatch/AppMatch/InterpreterQuery.s: AppMatch/AppMatch/InterpreterQuery.cpp.s

.PHONY : AppMatch/AppMatch/InterpreterQuery.s

# target to generate assembly for a file
AppMatch/AppMatch/InterpreterQuery.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/InterpreterQuery.cpp.s
.PHONY : AppMatch/AppMatch/InterpreterQuery.cpp.s

AppMatch/AppMatch/InterpreterRelationEngine.o: AppMatch/AppMatch/InterpreterRelationEngine.cpp.o

.PHONY : AppMatch/AppMatch/InterpreterRelationEngine.o

# target to build an object file
AppMatch/AppMatch/InterpreterRelationEngine.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/InterpreterRelationEngine.cpp.o
.PHONY : AppMatch/AppMatch/InterpreterRelationEngine.cpp.o

AppMatch/AppMatch/InterpreterRelationEngine.i: AppMatch/AppMatch/InterpreterRelationEngine.cpp.i

.PHONY : AppMatch/AppMatch/InterpreterRelationEngine.i

# target to preprocess a source file
AppMatch/AppMatch/InterpreterRelationEngine.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/InterpreterRelationEngine.cpp.i
.PHONY : AppMatch/AppMatch/InterpreterRelationEngine.cpp.i

AppMatch/AppMatch/InterpreterRelationEngine.s: AppMatch/AppMatch/InterpreterRelationEngine.cpp.s

.PHONY : AppMatch/AppMatch/InterpreterRelationEngine.s

# target to generate assembly for a file
AppMatch/AppMatch/InterpreterRelationEngine.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/InterpreterRelationEngine.cpp.s
.PHONY : AppMatch/AppMatch/InterpreterRelationEngine.cpp.s

AppMatch/AppMatch/ParseAssertationSecondary.o: AppMatch/AppMatch/ParseAssertationSecondary.cpp.o

.PHONY : AppMatch/AppMatch/ParseAssertationSecondary.o

# target to build an object file
AppMatch/AppMatch/ParseAssertationSecondary.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParseAssertationSecondary.cpp.o
.PHONY : AppMatch/AppMatch/ParseAssertationSecondary.cpp.o

AppMatch/AppMatch/ParseAssertationSecondary.i: AppMatch/AppMatch/ParseAssertationSecondary.cpp.i

.PHONY : AppMatch/AppMatch/ParseAssertationSecondary.i

# target to preprocess a source file
AppMatch/AppMatch/ParseAssertationSecondary.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParseAssertationSecondary.cpp.i
.PHONY : AppMatch/AppMatch/ParseAssertationSecondary.cpp.i

AppMatch/AppMatch/ParseAssertationSecondary.s: AppMatch/AppMatch/ParseAssertationSecondary.cpp.s

.PHONY : AppMatch/AppMatch/ParseAssertationSecondary.s

# target to generate assembly for a file
AppMatch/AppMatch/ParseAssertationSecondary.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParseAssertationSecondary.cpp.s
.PHONY : AppMatch/AppMatch/ParseAssertationSecondary.cpp.s

AppMatch/AppMatch/ParseDictionary.o: AppMatch/AppMatch/ParseDictionary.cpp.o

.PHONY : AppMatch/AppMatch/ParseDictionary.o

# target to build an object file
AppMatch/AppMatch/ParseDictionary.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParseDictionary.cpp.o
.PHONY : AppMatch/AppMatch/ParseDictionary.cpp.o

AppMatch/AppMatch/ParseDictionary.i: AppMatch/AppMatch/ParseDictionary.cpp.i

.PHONY : AppMatch/AppMatch/ParseDictionary.i

# target to preprocess a source file
AppMatch/AppMatch/ParseDictionary.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParseDictionary.cpp.i
.PHONY : AppMatch/AppMatch/ParseDictionary.cpp.i

AppMatch/AppMatch/ParseDictionary.s: AppMatch/AppMatch/ParseDictionary.cpp.s

.PHONY : AppMatch/AppMatch/ParseDictionary.s

# target to generate assembly for a file
AppMatch/AppMatch/ParseDictionary.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParseDictionary.cpp.s
.PHONY : AppMatch/AppMatch/ParseDictionary.cpp.s

AppMatch/AppMatch/ParseListAux.o: AppMatch/AppMatch/ParseListAux.cpp.o

.PHONY : AppMatch/AppMatch/ParseListAux.o

# target to build an object file
AppMatch/AppMatch/ParseListAux.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParseListAux.cpp.o
.PHONY : AppMatch/AppMatch/ParseListAux.cpp.o

AppMatch/AppMatch/ParseListAux.i: AppMatch/AppMatch/ParseListAux.cpp.i

.PHONY : AppMatch/AppMatch/ParseListAux.i

# target to preprocess a source file
AppMatch/AppMatch/ParseListAux.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParseListAux.cpp.i
.PHONY : AppMatch/AppMatch/ParseListAux.cpp.i

AppMatch/AppMatch/ParseListAux.s: AppMatch/AppMatch/ParseListAux.cpp.s

.PHONY : AppMatch/AppMatch/ParseListAux.s

# target to generate assembly for a file
AppMatch/AppMatch/ParseListAux.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParseListAux.cpp.s
.PHONY : AppMatch/AppMatch/ParseListAux.cpp.s

AppMatch/AppMatch/ParseRelation.o: AppMatch/AppMatch/ParseRelation.cpp.o

.PHONY : AppMatch/AppMatch/ParseRelation.o

# target to build an object file
AppMatch/AppMatch/ParseRelation.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParseRelation.cpp.o
.PHONY : AppMatch/AppMatch/ParseRelation.cpp.o

AppMatch/AppMatch/ParseRelation.i: AppMatch/AppMatch/ParseRelation.cpp.i

.PHONY : AppMatch/AppMatch/ParseRelation.i

# target to preprocess a source file
AppMatch/AppMatch/ParseRelation.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParseRelation.cpp.i
.PHONY : AppMatch/AppMatch/ParseRelation.cpp.i

AppMatch/AppMatch/ParseRelation.s: AppMatch/AppMatch/ParseRelation.cpp.s

.PHONY : AppMatch/AppMatch/ParseRelation.s

# target to generate assembly for a file
AppMatch/AppMatch/ParseRelation.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParseRelation.cpp.s
.PHONY : AppMatch/AppMatch/ParseRelation.cpp.s

AppMatch/AppMatch/ParseRelationWhen.o: AppMatch/AppMatch/ParseRelationWhen.cpp.o

.PHONY : AppMatch/AppMatch/ParseRelationWhen.o

# target to build an object file
AppMatch/AppMatch/ParseRelationWhen.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParseRelationWhen.cpp.o
.PHONY : AppMatch/AppMatch/ParseRelationWhen.cpp.o

AppMatch/AppMatch/ParseRelationWhen.i: AppMatch/AppMatch/ParseRelationWhen.cpp.i

.PHONY : AppMatch/AppMatch/ParseRelationWhen.i

# target to preprocess a source file
AppMatch/AppMatch/ParseRelationWhen.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParseRelationWhen.cpp.i
.PHONY : AppMatch/AppMatch/ParseRelationWhen.cpp.i

AppMatch/AppMatch/ParseRelationWhen.s: AppMatch/AppMatch/ParseRelationWhen.cpp.s

.PHONY : AppMatch/AppMatch/ParseRelationWhen.s

# target to generate assembly for a file
AppMatch/AppMatch/ParseRelationWhen.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParseRelationWhen.cpp.s
.PHONY : AppMatch/AppMatch/ParseRelationWhen.cpp.s

AppMatch/AppMatch/ParseVerbs.o: AppMatch/AppMatch/ParseVerbs.cpp.o

.PHONY : AppMatch/AppMatch/ParseVerbs.o

# target to build an object file
AppMatch/AppMatch/ParseVerbs.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParseVerbs.cpp.o
.PHONY : AppMatch/AppMatch/ParseVerbs.cpp.o

AppMatch/AppMatch/ParseVerbs.i: AppMatch/AppMatch/ParseVerbs.cpp.i

.PHONY : AppMatch/AppMatch/ParseVerbs.i

# target to preprocess a source file
AppMatch/AppMatch/ParseVerbs.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParseVerbs.cpp.i
.PHONY : AppMatch/AppMatch/ParseVerbs.cpp.i

AppMatch/AppMatch/ParseVerbs.s: AppMatch/AppMatch/ParseVerbs.cpp.s

.PHONY : AppMatch/AppMatch/ParseVerbs.s

# target to generate assembly for a file
AppMatch/AppMatch/ParseVerbs.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParseVerbs.cpp.s
.PHONY : AppMatch/AppMatch/ParseVerbs.cpp.s

AppMatch/AppMatch/Parse_TokensGroup.o: AppMatch/AppMatch/Parse_TokensGroup.cpp.o

.PHONY : AppMatch/AppMatch/Parse_TokensGroup.o

# target to build an object file
AppMatch/AppMatch/Parse_TokensGroup.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/Parse_TokensGroup.cpp.o
.PHONY : AppMatch/AppMatch/Parse_TokensGroup.cpp.o

AppMatch/AppMatch/Parse_TokensGroup.i: AppMatch/AppMatch/Parse_TokensGroup.cpp.i

.PHONY : AppMatch/AppMatch/Parse_TokensGroup.i

# target to preprocess a source file
AppMatch/AppMatch/Parse_TokensGroup.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/Parse_TokensGroup.cpp.i
.PHONY : AppMatch/AppMatch/Parse_TokensGroup.cpp.i

AppMatch/AppMatch/Parse_TokensGroup.s: AppMatch/AppMatch/Parse_TokensGroup.cpp.s

.PHONY : AppMatch/AppMatch/Parse_TokensGroup.s

# target to generate assembly for a file
AppMatch/AppMatch/Parse_TokensGroup.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/Parse_TokensGroup.cpp.s
.PHONY : AppMatch/AppMatch/Parse_TokensGroup.cpp.s

AppMatch/AppMatch/Parser.o: AppMatch/AppMatch/Parser.cpp.o

.PHONY : AppMatch/AppMatch/Parser.o

# target to build an object file
AppMatch/AppMatch/Parser.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/Parser.cpp.o
.PHONY : AppMatch/AppMatch/Parser.cpp.o

AppMatch/AppMatch/Parser.i: AppMatch/AppMatch/Parser.cpp.i

.PHONY : AppMatch/AppMatch/Parser.i

# target to preprocess a source file
AppMatch/AppMatch/Parser.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/Parser.cpp.i
.PHONY : AppMatch/AppMatch/Parser.cpp.i

AppMatch/AppMatch/Parser.s: AppMatch/AppMatch/Parser.cpp.s

.PHONY : AppMatch/AppMatch/Parser.s

# target to generate assembly for a file
AppMatch/AppMatch/Parser.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/Parser.cpp.s
.PHONY : AppMatch/AppMatch/Parser.cpp.s

AppMatch/AppMatch/ParserDynamicDispatch.o: AppMatch/AppMatch/ParserDynamicDispatch.cpp.o

.PHONY : AppMatch/AppMatch/ParserDynamicDispatch.o

# target to build an object file
AppMatch/AppMatch/ParserDynamicDispatch.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParserDynamicDispatch.cpp.o
.PHONY : AppMatch/AppMatch/ParserDynamicDispatch.cpp.o

AppMatch/AppMatch/ParserDynamicDispatch.i: AppMatch/AppMatch/ParserDynamicDispatch.cpp.i

.PHONY : AppMatch/AppMatch/ParserDynamicDispatch.i

# target to preprocess a source file
AppMatch/AppMatch/ParserDynamicDispatch.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParserDynamicDispatch.cpp.i
.PHONY : AppMatch/AppMatch/ParserDynamicDispatch.cpp.i

AppMatch/AppMatch/ParserDynamicDispatch.s: AppMatch/AppMatch/ParserDynamicDispatch.cpp.s

.PHONY : AppMatch/AppMatch/ParserDynamicDispatch.s

# target to generate assembly for a file
AppMatch/AppMatch/ParserDynamicDispatch.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParserDynamicDispatch.cpp.s
.PHONY : AppMatch/AppMatch/ParserDynamicDispatch.cpp.s

AppMatch/AppMatch/ParserPlural_table.o: AppMatch/AppMatch/ParserPlural_table.cpp.o

.PHONY : AppMatch/AppMatch/ParserPlural_table.o

# target to build an object file
AppMatch/AppMatch/ParserPlural_table.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParserPlural_table.cpp.o
.PHONY : AppMatch/AppMatch/ParserPlural_table.cpp.o

AppMatch/AppMatch/ParserPlural_table.i: AppMatch/AppMatch/ParserPlural_table.cpp.i

.PHONY : AppMatch/AppMatch/ParserPlural_table.i

# target to preprocess a source file
AppMatch/AppMatch/ParserPlural_table.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParserPlural_table.cpp.i
.PHONY : AppMatch/AppMatch/ParserPlural_table.cpp.i

AppMatch/AppMatch/ParserPlural_table.s: AppMatch/AppMatch/ParserPlural_table.cpp.s

.PHONY : AppMatch/AppMatch/ParserPlural_table.s

# target to generate assembly for a file
AppMatch/AppMatch/ParserPlural_table.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParserPlural_table.cpp.s
.PHONY : AppMatch/AppMatch/ParserPlural_table.cpp.s

AppMatch/AppMatch/ParserSelectorFunctional.o: AppMatch/AppMatch/ParserSelectorFunctional.cpp.o

.PHONY : AppMatch/AppMatch/ParserSelectorFunctional.o

# target to build an object file
AppMatch/AppMatch/ParserSelectorFunctional.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParserSelectorFunctional.cpp.o
.PHONY : AppMatch/AppMatch/ParserSelectorFunctional.cpp.o

AppMatch/AppMatch/ParserSelectorFunctional.i: AppMatch/AppMatch/ParserSelectorFunctional.cpp.i

.PHONY : AppMatch/AppMatch/ParserSelectorFunctional.i

# target to preprocess a source file
AppMatch/AppMatch/ParserSelectorFunctional.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParserSelectorFunctional.cpp.i
.PHONY : AppMatch/AppMatch/ParserSelectorFunctional.cpp.i

AppMatch/AppMatch/ParserSelectorFunctional.s: AppMatch/AppMatch/ParserSelectorFunctional.cpp.s

.PHONY : AppMatch/AppMatch/ParserSelectorFunctional.s

# target to generate assembly for a file
AppMatch/AppMatch/ParserSelectorFunctional.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParserSelectorFunctional.cpp.s
.PHONY : AppMatch/AppMatch/ParserSelectorFunctional.cpp.s

AppMatch/AppMatch/ParserStmt.o: AppMatch/AppMatch/ParserStmt.cpp.o

.PHONY : AppMatch/AppMatch/ParserStmt.o

# target to build an object file
AppMatch/AppMatch/ParserStmt.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParserStmt.cpp.o
.PHONY : AppMatch/AppMatch/ParserStmt.cpp.o

AppMatch/AppMatch/ParserStmt.i: AppMatch/AppMatch/ParserStmt.cpp.i

.PHONY : AppMatch/AppMatch/ParserStmt.i

# target to preprocess a source file
AppMatch/AppMatch/ParserStmt.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParserStmt.cpp.i
.PHONY : AppMatch/AppMatch/ParserStmt.cpp.i

AppMatch/AppMatch/ParserStmt.s: AppMatch/AppMatch/ParserStmt.cpp.s

.PHONY : AppMatch/AppMatch/ParserStmt.s

# target to generate assembly for a file
AppMatch/AppMatch/ParserStmt.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParserStmt.cpp.s
.PHONY : AppMatch/AppMatch/ParserStmt.cpp.s

AppMatch/AppMatch/ParserTextEntry.o: AppMatch/AppMatch/ParserTextEntry.cpp.o

.PHONY : AppMatch/AppMatch/ParserTextEntry.o

# target to build an object file
AppMatch/AppMatch/ParserTextEntry.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParserTextEntry.cpp.o
.PHONY : AppMatch/AppMatch/ParserTextEntry.cpp.o

AppMatch/AppMatch/ParserTextEntry.i: AppMatch/AppMatch/ParserTextEntry.cpp.i

.PHONY : AppMatch/AppMatch/ParserTextEntry.i

# target to preprocess a source file
AppMatch/AppMatch/ParserTextEntry.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParserTextEntry.cpp.i
.PHONY : AppMatch/AppMatch/ParserTextEntry.cpp.i

AppMatch/AppMatch/ParserTextEntry.s: AppMatch/AppMatch/ParserTextEntry.cpp.s

.PHONY : AppMatch/AppMatch/ParserTextEntry.s

# target to generate assembly for a file
AppMatch/AppMatch/ParserTextEntry.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/ParserTextEntry.cpp.s
.PHONY : AppMatch/AppMatch/ParserTextEntry.cpp.s

AppMatch/AppMatch/Parser_A.o: AppMatch/AppMatch/Parser_A.cpp.o

.PHONY : AppMatch/AppMatch/Parser_A.o

# target to build an object file
AppMatch/AppMatch/Parser_A.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/Parser_A.cpp.o
.PHONY : AppMatch/AppMatch/Parser_A.cpp.o

AppMatch/AppMatch/Parser_A.i: AppMatch/AppMatch/Parser_A.cpp.i

.PHONY : AppMatch/AppMatch/Parser_A.i

# target to preprocess a source file
AppMatch/AppMatch/Parser_A.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/Parser_A.cpp.i
.PHONY : AppMatch/AppMatch/Parser_A.cpp.i

AppMatch/AppMatch/Parser_A.s: AppMatch/AppMatch/Parser_A.cpp.s

.PHONY : AppMatch/AppMatch/Parser_A.s

# target to generate assembly for a file
AppMatch/AppMatch/Parser_A.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/Parser_A.cpp.s
.PHONY : AppMatch/AppMatch/Parser_A.cpp.s

AppMatch/AppMatch/Parser_ActionControl.o: AppMatch/AppMatch/Parser_ActionControl.cpp.o

.PHONY : AppMatch/AppMatch/Parser_ActionControl.o

# target to build an object file
AppMatch/AppMatch/Parser_ActionControl.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/Parser_ActionControl.cpp.o
.PHONY : AppMatch/AppMatch/Parser_ActionControl.cpp.o

AppMatch/AppMatch/Parser_ActionControl.i: AppMatch/AppMatch/Parser_ActionControl.cpp.i

.PHONY : AppMatch/AppMatch/Parser_ActionControl.i

# target to preprocess a source file
AppMatch/AppMatch/Parser_ActionControl.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/Parser_ActionControl.cpp.i
.PHONY : AppMatch/AppMatch/Parser_ActionControl.cpp.i

AppMatch/AppMatch/Parser_ActionControl.s: AppMatch/AppMatch/Parser_ActionControl.cpp.s

.PHONY : AppMatch/AppMatch/Parser_ActionControl.s

# target to generate assembly for a file
AppMatch/AppMatch/Parser_ActionControl.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/Parser_ActionControl.cpp.s
.PHONY : AppMatch/AppMatch/Parser_ActionControl.cpp.s

AppMatch/AppMatch/Parser_ControlFlux.o: AppMatch/AppMatch/Parser_ControlFlux.cpp.o

.PHONY : AppMatch/AppMatch/Parser_ControlFlux.o

# target to build an object file
AppMatch/AppMatch/Parser_ControlFlux.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/Parser_ControlFlux.cpp.o
.PHONY : AppMatch/AppMatch/Parser_ControlFlux.cpp.o

AppMatch/AppMatch/Parser_ControlFlux.i: AppMatch/AppMatch/Parser_ControlFlux.cpp.i

.PHONY : AppMatch/AppMatch/Parser_ControlFlux.i

# target to preprocess a source file
AppMatch/AppMatch/Parser_ControlFlux.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/Parser_ControlFlux.cpp.i
.PHONY : AppMatch/AppMatch/Parser_ControlFlux.cpp.i

AppMatch/AppMatch/Parser_ControlFlux.s: AppMatch/AppMatch/Parser_ControlFlux.cpp.s

.PHONY : AppMatch/AppMatch/Parser_ControlFlux.s

# target to generate assembly for a file
AppMatch/AppMatch/Parser_ControlFlux.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/Parser_ControlFlux.cpp.s
.PHONY : AppMatch/AppMatch/Parser_ControlFlux.cpp.s

AppMatch/AppMatch/Parser_Decide.o: AppMatch/AppMatch/Parser_Decide.cpp.o

.PHONY : AppMatch/AppMatch/Parser_Decide.o

# target to build an object file
AppMatch/AppMatch/Parser_Decide.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/Parser_Decide.cpp.o
.PHONY : AppMatch/AppMatch/Parser_Decide.cpp.o

AppMatch/AppMatch/Parser_Decide.i: AppMatch/AppMatch/Parser_Decide.cpp.i

.PHONY : AppMatch/AppMatch/Parser_Decide.i

# target to preprocess a source file
AppMatch/AppMatch/Parser_Decide.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/Parser_Decide.cpp.i
.PHONY : AppMatch/AppMatch/Parser_Decide.cpp.i

AppMatch/AppMatch/Parser_Decide.s: AppMatch/AppMatch/Parser_Decide.cpp.s

.PHONY : AppMatch/AppMatch/Parser_Decide.s

# target to generate assembly for a file
AppMatch/AppMatch/Parser_Decide.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/Parser_Decide.cpp.s
.PHONY : AppMatch/AppMatch/Parser_Decide.cpp.s

AppMatch/AppMatch/Parser_Plurals_En.o: AppMatch/AppMatch/Parser_Plurals_En.cpp.o

.PHONY : AppMatch/AppMatch/Parser_Plurals_En.o

# target to build an object file
AppMatch/AppMatch/Parser_Plurals_En.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/Parser_Plurals_En.cpp.o
.PHONY : AppMatch/AppMatch/Parser_Plurals_En.cpp.o

AppMatch/AppMatch/Parser_Plurals_En.i: AppMatch/AppMatch/Parser_Plurals_En.cpp.i

.PHONY : AppMatch/AppMatch/Parser_Plurals_En.i

# target to preprocess a source file
AppMatch/AppMatch/Parser_Plurals_En.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/Parser_Plurals_En.cpp.i
.PHONY : AppMatch/AppMatch/Parser_Plurals_En.cpp.i

AppMatch/AppMatch/Parser_Plurals_En.s: AppMatch/AppMatch/Parser_Plurals_En.cpp.s

.PHONY : AppMatch/AppMatch/Parser_Plurals_En.s

# target to generate assembly for a file
AppMatch/AppMatch/Parser_Plurals_En.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/Parser_Plurals_En.cpp.s
.PHONY : AppMatch/AppMatch/Parser_Plurals_En.cpp.s

AppMatch/AppMatch/Parser_RegisterVerb.o: AppMatch/AppMatch/Parser_RegisterVerb.cpp.o

.PHONY : AppMatch/AppMatch/Parser_RegisterVerb.o

# target to build an object file
AppMatch/AppMatch/Parser_RegisterVerb.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/Parser_RegisterVerb.cpp.o
.PHONY : AppMatch/AppMatch/Parser_RegisterVerb.cpp.o

AppMatch/AppMatch/Parser_RegisterVerb.i: AppMatch/AppMatch/Parser_RegisterVerb.cpp.i

.PHONY : AppMatch/AppMatch/Parser_RegisterVerb.i

# target to preprocess a source file
AppMatch/AppMatch/Parser_RegisterVerb.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/Parser_RegisterVerb.cpp.i
.PHONY : AppMatch/AppMatch/Parser_RegisterVerb.cpp.i

AppMatch/AppMatch/Parser_RegisterVerb.s: AppMatch/AppMatch/Parser_RegisterVerb.cpp.s

.PHONY : AppMatch/AppMatch/Parser_RegisterVerb.s

# target to generate assembly for a file
AppMatch/AppMatch/Parser_RegisterVerb.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/Parser_RegisterVerb.cpp.s
.PHONY : AppMatch/AppMatch/Parser_RegisterVerb.cpp.s

AppMatch/AppMatch/Parser_VerbTable_en.o: AppMatch/AppMatch/Parser_VerbTable_en.cpp.o

.PHONY : AppMatch/AppMatch/Parser_VerbTable_en.o

# target to build an object file
AppMatch/AppMatch/Parser_VerbTable_en.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/Parser_VerbTable_en.cpp.o
.PHONY : AppMatch/AppMatch/Parser_VerbTable_en.cpp.o

AppMatch/AppMatch/Parser_VerbTable_en.i: AppMatch/AppMatch/Parser_VerbTable_en.cpp.i

.PHONY : AppMatch/AppMatch/Parser_VerbTable_en.i

# target to preprocess a source file
AppMatch/AppMatch/Parser_VerbTable_en.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/Parser_VerbTable_en.cpp.i
.PHONY : AppMatch/AppMatch/Parser_VerbTable_en.cpp.i

AppMatch/AppMatch/Parser_VerbTable_en.s: AppMatch/AppMatch/Parser_VerbTable_en.cpp.s

.PHONY : AppMatch/AppMatch/Parser_VerbTable_en.s

# target to generate assembly for a file
AppMatch/AppMatch/Parser_VerbTable_en.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/Parser_VerbTable_en.cpp.s
.PHONY : AppMatch/AppMatch/Parser_VerbTable_en.cpp.s

AppMatch/AppMatch/Parser_expression_match.o: AppMatch/AppMatch/Parser_expression_match.cpp.o

.PHONY : AppMatch/AppMatch/Parser_expression_match.o

# target to build an object file
AppMatch/AppMatch/Parser_expression_match.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/Parser_expression_match.cpp.o
.PHONY : AppMatch/AppMatch/Parser_expression_match.cpp.o

AppMatch/AppMatch/Parser_expression_match.i: AppMatch/AppMatch/Parser_expression_match.cpp.i

.PHONY : AppMatch/AppMatch/Parser_expression_match.i

# target to preprocess a source file
AppMatch/AppMatch/Parser_expression_match.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/Parser_expression_match.cpp.i
.PHONY : AppMatch/AppMatch/Parser_expression_match.cpp.i

AppMatch/AppMatch/Parser_expression_match.s: AppMatch/AppMatch/Parser_expression_match.cpp.s

.PHONY : AppMatch/AppMatch/Parser_expression_match.s

# target to generate assembly for a file
AppMatch/AppMatch/Parser_expression_match.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/Parser_expression_match.cpp.s
.PHONY : AppMatch/AppMatch/Parser_expression_match.cpp.s

AppMatch/AppMatch/QueryItem.o: AppMatch/AppMatch/QueryItem.cpp.o

.PHONY : AppMatch/AppMatch/QueryItem.o

# target to build an object file
AppMatch/AppMatch/QueryItem.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/QueryItem.cpp.o
.PHONY : AppMatch/AppMatch/QueryItem.cpp.o

AppMatch/AppMatch/QueryItem.i: AppMatch/AppMatch/QueryItem.cpp.i

.PHONY : AppMatch/AppMatch/QueryItem.i

# target to preprocess a source file
AppMatch/AppMatch/QueryItem.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/QueryItem.cpp.i
.PHONY : AppMatch/AppMatch/QueryItem.cpp.i

AppMatch/AppMatch/QueryItem.s: AppMatch/AppMatch/QueryItem.cpp.s

.PHONY : AppMatch/AppMatch/QueryItem.s

# target to generate assembly for a file
AppMatch/AppMatch/QueryItem.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/QueryItem.cpp.s
.PHONY : AppMatch/AppMatch/QueryItem.cpp.s

AppMatch/AppMatch/RuntimeErrors.o: AppMatch/AppMatch/RuntimeErrors.cpp.o

.PHONY : AppMatch/AppMatch/RuntimeErrors.o

# target to build an object file
AppMatch/AppMatch/RuntimeErrors.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/RuntimeErrors.cpp.o
.PHONY : AppMatch/AppMatch/RuntimeErrors.cpp.o

AppMatch/AppMatch/RuntimeErrors.i: AppMatch/AppMatch/RuntimeErrors.cpp.i

.PHONY : AppMatch/AppMatch/RuntimeErrors.i

# target to preprocess a source file
AppMatch/AppMatch/RuntimeErrors.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/RuntimeErrors.cpp.i
.PHONY : AppMatch/AppMatch/RuntimeErrors.cpp.i

AppMatch/AppMatch/RuntimeErrors.s: AppMatch/AppMatch/RuntimeErrors.cpp.s

.PHONY : AppMatch/AppMatch/RuntimeErrors.s

# target to generate assembly for a file
AppMatch/AppMatch/RuntimeErrors.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/RuntimeErrors.cpp.s
.PHONY : AppMatch/AppMatch/RuntimeErrors.cpp.s

AppMatch/AppMatch/StaticDispatchFunctions.o: AppMatch/AppMatch/StaticDispatchFunctions.cpp.o

.PHONY : AppMatch/AppMatch/StaticDispatchFunctions.o

# target to build an object file
AppMatch/AppMatch/StaticDispatchFunctions.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/StaticDispatchFunctions.cpp.o
.PHONY : AppMatch/AppMatch/StaticDispatchFunctions.cpp.o

AppMatch/AppMatch/StaticDispatchFunctions.i: AppMatch/AppMatch/StaticDispatchFunctions.cpp.i

.PHONY : AppMatch/AppMatch/StaticDispatchFunctions.i

# target to preprocess a source file
AppMatch/AppMatch/StaticDispatchFunctions.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/StaticDispatchFunctions.cpp.i
.PHONY : AppMatch/AppMatch/StaticDispatchFunctions.cpp.i

AppMatch/AppMatch/StaticDispatchFunctions.s: AppMatch/AppMatch/StaticDispatchFunctions.cpp.s

.PHONY : AppMatch/AppMatch/StaticDispatchFunctions.s

# target to generate assembly for a file
AppMatch/AppMatch/StaticDispatchFunctions.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/StaticDispatchFunctions.cpp.s
.PHONY : AppMatch/AppMatch/StaticDispatchFunctions.cpp.s

AppMatch/AppMatch/dynamicCast.o: AppMatch/AppMatch/dynamicCast.cpp.o

.PHONY : AppMatch/AppMatch/dynamicCast.o

# target to build an object file
AppMatch/AppMatch/dynamicCast.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/dynamicCast.cpp.o
.PHONY : AppMatch/AppMatch/dynamicCast.cpp.o

AppMatch/AppMatch/dynamicCast.i: AppMatch/AppMatch/dynamicCast.cpp.i

.PHONY : AppMatch/AppMatch/dynamicCast.i

# target to preprocess a source file
AppMatch/AppMatch/dynamicCast.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/dynamicCast.cpp.i
.PHONY : AppMatch/AppMatch/dynamicCast.cpp.i

AppMatch/AppMatch/dynamicCast.s: AppMatch/AppMatch/dynamicCast.cpp.s

.PHONY : AppMatch/AppMatch/dynamicCast.s

# target to generate assembly for a file
AppMatch/AppMatch/dynamicCast.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/dynamicCast.cpp.s
.PHONY : AppMatch/AppMatch/dynamicCast.cpp.s

AppMatch/AppMatch/sharedCast.o: AppMatch/AppMatch/sharedCast.cpp.o

.PHONY : AppMatch/AppMatch/sharedCast.o

# target to build an object file
AppMatch/AppMatch/sharedCast.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/sharedCast.cpp.o
.PHONY : AppMatch/AppMatch/sharedCast.cpp.o

AppMatch/AppMatch/sharedCast.i: AppMatch/AppMatch/sharedCast.cpp.i

.PHONY : AppMatch/AppMatch/sharedCast.i

# target to preprocess a source file
AppMatch/AppMatch/sharedCast.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/sharedCast.cpp.i
.PHONY : AppMatch/AppMatch/sharedCast.cpp.i

AppMatch/AppMatch/sharedCast.s: AppMatch/AppMatch/sharedCast.cpp.s

.PHONY : AppMatch/AppMatch/sharedCast.s

# target to generate assembly for a file
AppMatch/AppMatch/sharedCast.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/sharedCast.cpp.s
.PHONY : AppMatch/AppMatch/sharedCast.cpp.s

AppMatch/AppMatch/stdafx.o: AppMatch/AppMatch/stdafx.cpp.o

.PHONY : AppMatch/AppMatch/stdafx.o

# target to build an object file
AppMatch/AppMatch/stdafx.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/stdafx.cpp.o
.PHONY : AppMatch/AppMatch/stdafx.cpp.o

AppMatch/AppMatch/stdafx.i: AppMatch/AppMatch/stdafx.cpp.i

.PHONY : AppMatch/AppMatch/stdafx.i

# target to preprocess a source file
AppMatch/AppMatch/stdafx.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/stdafx.cpp.i
.PHONY : AppMatch/AppMatch/stdafx.cpp.i

AppMatch/AppMatch/stdafx.s: AppMatch/AppMatch/stdafx.cpp.s

.PHONY : AppMatch/AppMatch/stdafx.s

# target to generate assembly for a file
AppMatch/AppMatch/stdafx.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/stdafx.cpp.s
.PHONY : AppMatch/AppMatch/stdafx.cpp.s

AppMatch/AppMatch/testeLista.o: AppMatch/AppMatch/testeLista.cpp.o

.PHONY : AppMatch/AppMatch/testeLista.o

# target to build an object file
AppMatch/AppMatch/testeLista.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/testeLista.cpp.o
.PHONY : AppMatch/AppMatch/testeLista.cpp.o

AppMatch/AppMatch/testeLista.i: AppMatch/AppMatch/testeLista.cpp.i

.PHONY : AppMatch/AppMatch/testeLista.i

# target to preprocess a source file
AppMatch/AppMatch/testeLista.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/testeLista.cpp.i
.PHONY : AppMatch/AppMatch/testeLista.cpp.i

AppMatch/AppMatch/testeLista.s: AppMatch/AppMatch/testeLista.cpp.s

.PHONY : AppMatch/AppMatch/testeLista.s

# target to generate assembly for a file
AppMatch/AppMatch/testeLista.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/testeLista.cpp.s
.PHONY : AppMatch/AppMatch/testeLista.cpp.s

AppMatch/AppMatch/testeSerialize.o: AppMatch/AppMatch/testeSerialize.cpp.o

.PHONY : AppMatch/AppMatch/testeSerialize.o

# target to build an object file
AppMatch/AppMatch/testeSerialize.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/testeSerialize.cpp.o
.PHONY : AppMatch/AppMatch/testeSerialize.cpp.o

AppMatch/AppMatch/testeSerialize.i: AppMatch/AppMatch/testeSerialize.cpp.i

.PHONY : AppMatch/AppMatch/testeSerialize.i

# target to preprocess a source file
AppMatch/AppMatch/testeSerialize.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/testeSerialize.cpp.i
.PHONY : AppMatch/AppMatch/testeSerialize.cpp.i

AppMatch/AppMatch/testeSerialize.s: AppMatch/AppMatch/testeSerialize.cpp.s

.PHONY : AppMatch/AppMatch/testeSerialize.s

# target to generate assembly for a file
AppMatch/AppMatch/testeSerialize.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/testeSerialize.cpp.s
.PHONY : AppMatch/AppMatch/testeSerialize.cpp.s

AppMatch/AppMatch/teste_action.o: AppMatch/AppMatch/teste_action.cpp.o

.PHONY : AppMatch/AppMatch/teste_action.o

# target to build an object file
AppMatch/AppMatch/teste_action.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/teste_action.cpp.o
.PHONY : AppMatch/AppMatch/teste_action.cpp.o

AppMatch/AppMatch/teste_action.i: AppMatch/AppMatch/teste_action.cpp.i

.PHONY : AppMatch/AppMatch/teste_action.i

# target to preprocess a source file
AppMatch/AppMatch/teste_action.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/teste_action.cpp.i
.PHONY : AppMatch/AppMatch/teste_action.cpp.i

AppMatch/AppMatch/teste_action.s: AppMatch/AppMatch/teste_action.cpp.s

.PHONY : AppMatch/AppMatch/teste_action.s

# target to generate assembly for a file
AppMatch/AppMatch/teste_action.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/teste_action.cpp.s
.PHONY : AppMatch/AppMatch/teste_action.cpp.s

AppMatch/AppMatch/teste_composition.o: AppMatch/AppMatch/teste_composition.cpp.o

.PHONY : AppMatch/AppMatch/teste_composition.o

# target to build an object file
AppMatch/AppMatch/teste_composition.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/teste_composition.cpp.o
.PHONY : AppMatch/AppMatch/teste_composition.cpp.o

AppMatch/AppMatch/teste_composition.i: AppMatch/AppMatch/teste_composition.cpp.i

.PHONY : AppMatch/AppMatch/teste_composition.i

# target to preprocess a source file
AppMatch/AppMatch/teste_composition.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/teste_composition.cpp.i
.PHONY : AppMatch/AppMatch/teste_composition.cpp.i

AppMatch/AppMatch/teste_composition.s: AppMatch/AppMatch/teste_composition.cpp.s

.PHONY : AppMatch/AppMatch/teste_composition.s

# target to generate assembly for a file
AppMatch/AppMatch/teste_composition.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/teste_composition.cpp.s
.PHONY : AppMatch/AppMatch/teste_composition.cpp.s

AppMatch/AppMatch/teste_selector.o: AppMatch/AppMatch/teste_selector.cpp.o

.PHONY : AppMatch/AppMatch/teste_selector.o

# target to build an object file
AppMatch/AppMatch/teste_selector.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/teste_selector.cpp.o
.PHONY : AppMatch/AppMatch/teste_selector.cpp.o

AppMatch/AppMatch/teste_selector.i: AppMatch/AppMatch/teste_selector.cpp.i

.PHONY : AppMatch/AppMatch/teste_selector.i

# target to preprocess a source file
AppMatch/AppMatch/teste_selector.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/teste_selector.cpp.i
.PHONY : AppMatch/AppMatch/teste_selector.cpp.i

AppMatch/AppMatch/teste_selector.s: AppMatch/AppMatch/teste_selector.cpp.s

.PHONY : AppMatch/AppMatch/teste_selector.s

# target to generate assembly for a file
AppMatch/AppMatch/teste_selector.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/teste_selector.cpp.s
.PHONY : AppMatch/AppMatch/teste_selector.cpp.s

AppMatch/AppMatch/teste_verb.o: AppMatch/AppMatch/teste_verb.cpp.o

.PHONY : AppMatch/AppMatch/teste_verb.o

# target to build an object file
AppMatch/AppMatch/teste_verb.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/teste_verb.cpp.o
.PHONY : AppMatch/AppMatch/teste_verb.cpp.o

AppMatch/AppMatch/teste_verb.i: AppMatch/AppMatch/teste_verb.cpp.i

.PHONY : AppMatch/AppMatch/teste_verb.i

# target to preprocess a source file
AppMatch/AppMatch/teste_verb.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/teste_verb.cpp.i
.PHONY : AppMatch/AppMatch/teste_verb.cpp.i

AppMatch/AppMatch/teste_verb.s: AppMatch/AppMatch/teste_verb.cpp.s

.PHONY : AppMatch/AppMatch/teste_verb.s

# target to generate assembly for a file
AppMatch/AppMatch/teste_verb.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/teste_verb.cpp.s
.PHONY : AppMatch/AppMatch/teste_verb.cpp.s

AppMatch/AppMatch/testesParser.o: AppMatch/AppMatch/testesParser.cpp.o

.PHONY : AppMatch/AppMatch/testesParser.o

# target to build an object file
AppMatch/AppMatch/testesParser.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/testesParser.cpp.o
.PHONY : AppMatch/AppMatch/testesParser.cpp.o

AppMatch/AppMatch/testesParser.i: AppMatch/AppMatch/testesParser.cpp.i

.PHONY : AppMatch/AppMatch/testesParser.i

# target to preprocess a source file
AppMatch/AppMatch/testesParser.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/testesParser.cpp.i
.PHONY : AppMatch/AppMatch/testesParser.cpp.i

AppMatch/AppMatch/testesParser.s: AppMatch/AppMatch/testesParser.cpp.s

.PHONY : AppMatch/AppMatch/testesParser.s

# target to generate assembly for a file
AppMatch/AppMatch/testesParser.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/testesParser.cpp.s
.PHONY : AppMatch/AppMatch/testesParser.cpp.s

AppMatch/AppMatch/testes_1.o: AppMatch/AppMatch/testes_1.cpp.o

.PHONY : AppMatch/AppMatch/testes_1.o

# target to build an object file
AppMatch/AppMatch/testes_1.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/testes_1.cpp.o
.PHONY : AppMatch/AppMatch/testes_1.cpp.o

AppMatch/AppMatch/testes_1.i: AppMatch/AppMatch/testes_1.cpp.i

.PHONY : AppMatch/AppMatch/testes_1.i

# target to preprocess a source file
AppMatch/AppMatch/testes_1.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/testes_1.cpp.i
.PHONY : AppMatch/AppMatch/testes_1.cpp.i

AppMatch/AppMatch/testes_1.s: AppMatch/AppMatch/testes_1.cpp.s

.PHONY : AppMatch/AppMatch/testes_1.s

# target to generate assembly for a file
AppMatch/AppMatch/testes_1.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/testes_1.cpp.s
.PHONY : AppMatch/AppMatch/testes_1.cpp.s

AppMatch/AppMatch/testes_2.o: AppMatch/AppMatch/testes_2.cpp.o

.PHONY : AppMatch/AppMatch/testes_2.o

# target to build an object file
AppMatch/AppMatch/testes_2.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/testes_2.cpp.o
.PHONY : AppMatch/AppMatch/testes_2.cpp.o

AppMatch/AppMatch/testes_2.i: AppMatch/AppMatch/testes_2.cpp.i

.PHONY : AppMatch/AppMatch/testes_2.i

# target to preprocess a source file
AppMatch/AppMatch/testes_2.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/testes_2.cpp.i
.PHONY : AppMatch/AppMatch/testes_2.cpp.i

AppMatch/AppMatch/testes_2.s: AppMatch/AppMatch/testes_2.cpp.s

.PHONY : AppMatch/AppMatch/testes_2.s

# target to generate assembly for a file
AppMatch/AppMatch/testes_2.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/testes_2.cpp.s
.PHONY : AppMatch/AppMatch/testes_2.cpp.s

AppMatch/AppMatch/testes_Relation.o: AppMatch/AppMatch/testes_Relation.cpp.o

.PHONY : AppMatch/AppMatch/testes_Relation.o

# target to build an object file
AppMatch/AppMatch/testes_Relation.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/testes_Relation.cpp.o
.PHONY : AppMatch/AppMatch/testes_Relation.cpp.o

AppMatch/AppMatch/testes_Relation.i: AppMatch/AppMatch/testes_Relation.cpp.i

.PHONY : AppMatch/AppMatch/testes_Relation.i

# target to preprocess a source file
AppMatch/AppMatch/testes_Relation.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/testes_Relation.cpp.i
.PHONY : AppMatch/AppMatch/testes_Relation.cpp.i

AppMatch/AppMatch/testes_Relation.s: AppMatch/AppMatch/testes_Relation.cpp.s

.PHONY : AppMatch/AppMatch/testes_Relation.s

# target to generate assembly for a file
AppMatch/AppMatch/testes_Relation.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/testes_Relation.cpp.s
.PHONY : AppMatch/AppMatch/testes_Relation.cpp.s

AppMatch/AppMatch/testes_decide.o: AppMatch/AppMatch/testes_decide.cpp.o

.PHONY : AppMatch/AppMatch/testes_decide.o

# target to build an object file
AppMatch/AppMatch/testes_decide.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/testes_decide.cpp.o
.PHONY : AppMatch/AppMatch/testes_decide.cpp.o

AppMatch/AppMatch/testes_decide.i: AppMatch/AppMatch/testes_decide.cpp.i

.PHONY : AppMatch/AppMatch/testes_decide.i

# target to preprocess a source file
AppMatch/AppMatch/testes_decide.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/testes_decide.cpp.i
.PHONY : AppMatch/AppMatch/testes_decide.cpp.i

AppMatch/AppMatch/testes_decide.s: AppMatch/AppMatch/testes_decide.cpp.s

.PHONY : AppMatch/AppMatch/testes_decide.s

# target to generate assembly for a file
AppMatch/AppMatch/testes_decide.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/testes_decide.cpp.s
.PHONY : AppMatch/AppMatch/testes_decide.cpp.s

AppMatch/AppMatch/testes_execute.o: AppMatch/AppMatch/testes_execute.cpp.o

.PHONY : AppMatch/AppMatch/testes_execute.o

# target to build an object file
AppMatch/AppMatch/testes_execute.cpp.o:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/testes_execute.cpp.o
.PHONY : AppMatch/AppMatch/testes_execute.cpp.o

AppMatch/AppMatch/testes_execute.i: AppMatch/AppMatch/testes_execute.cpp.i

.PHONY : AppMatch/AppMatch/testes_execute.i

# target to preprocess a source file
AppMatch/AppMatch/testes_execute.cpp.i:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/testes_execute.cpp.i
.PHONY : AppMatch/AppMatch/testes_execute.cpp.i

AppMatch/AppMatch/testes_execute.s: AppMatch/AppMatch/testes_execute.cpp.s

.PHONY : AppMatch/AppMatch/testes_execute.s

# target to generate assembly for a file
AppMatch/AppMatch/testes_execute.cpp.s:
	$(MAKE) -f CMakeFiles/apx.dir/build.make CMakeFiles/apx.dir/AppMatch/AppMatch/testes_execute.cpp.s
.PHONY : AppMatch/AppMatch/testes_execute.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... apx"
	@echo "... AppMatch/AppMatch/AssertationDefaultValue.o"
	@echo "... AppMatch/AppMatch/AssertationDefaultValue.i"
	@echo "... AppMatch/AppMatch/AssertationDefaultValue.s"
	@echo "... AppMatch/AppMatch/AssertationEngine.o"
	@echo "... AppMatch/AppMatch/AssertationEngine.i"
	@echo "... AppMatch/AppMatch/AssertationEngine.s"
	@echo "... AppMatch/AppMatch/AssertationVerbRelation.o"
	@echo "... AppMatch/AppMatch/AssertationVerbRelation.i"
	@echo "... AppMatch/AppMatch/AssertationVerbRelation.s"
	@echo "... AppMatch/AppMatch/AssertionValues.o"
	@echo "... AppMatch/AppMatch/AssertionValues.i"
	@echo "... AppMatch/AppMatch/AssertionValues.s"
	@echo "... AppMatch/AppMatch/BlockInstance.o"
	@echo "... AppMatch/AppMatch/BlockInstance.i"
	@echo "... AppMatch/AppMatch/BlockInstance.s"
	@echo "... AppMatch/AppMatch/BlockInterpreter.o"
	@echo "... AppMatch/AppMatch/BlockInterpreter.i"
	@echo "... AppMatch/AppMatch/BlockInterpreter.s"
	@echo "... AppMatch/AppMatch/BlockisSame.o"
	@echo "... AppMatch/AppMatch/BlockisSame.i"
	@echo "... AppMatch/AppMatch/BlockisSame.s"
	@echo "... AppMatch/AppMatch/CBase.o"
	@echo "... AppMatch/AppMatch/CBase.i"
	@echo "... AppMatch/AppMatch/CBase.s"
	@echo "... AppMatch/AppMatch/CBlockDumpValues.o"
	@echo "... AppMatch/AppMatch/CBlockDumpValues.i"
	@echo "... AppMatch/AppMatch/CBlockDumpValues.s"
	@echo "... AppMatch/AppMatch/CBlockInterpreterDecideBody.o"
	@echo "... AppMatch/AppMatch/CBlockInterpreterDecideBody.i"
	@echo "... AppMatch/AppMatch/CBlockInterpreterDecideBody.s"
	@echo "... AppMatch/AppMatch/CBlockInterpreterRuntime.o"
	@echo "... AppMatch/AppMatch/CBlockInterpreterRuntime.i"
	@echo "... AppMatch/AppMatch/CBlockInterpreterRuntime.s"
	@echo "... AppMatch/AppMatch/CBlockInterpreter_Verb_En.o"
	@echo "... AppMatch/AppMatch/CBlockInterpreter_Verb_En.i"
	@echo "... AppMatch/AppMatch/CBlockInterpreter_Verb_En.s"
	@echo "... AppMatch/AppMatch/CBlockSerialize.o"
	@echo "... AppMatch/AppMatch/CBlockSerialize.i"
	@echo "... AppMatch/AppMatch/CBlockSerialize.s"
	@echo "... AppMatch/AppMatch/CDataMananger.o"
	@echo "... AppMatch/AppMatch/CDataMananger.i"
	@echo "... AppMatch/AppMatch/CDataMananger.s"
	@echo "... AppMatch/AppMatch/CInterpreterEvaluate.o"
	@echo "... AppMatch/AppMatch/CInterpreterEvaluate.i"
	@echo "... AppMatch/AppMatch/CInterpreterEvaluate.s"
	@echo "... AppMatch/AppMatch/CInterpreterKindTree.o"
	@echo "... AppMatch/AppMatch/CInterpreterKindTree.i"
	@echo "... AppMatch/AppMatch/CInterpreterKindTree.s"
	@echo "... AppMatch/AppMatch/CInterpreterRelation.o"
	@echo "... AppMatch/AppMatch/CInterpreterRelation.i"
	@echo "... AppMatch/AppMatch/CInterpreterRelation.s"
	@echo "... AppMatch/AppMatch/CInterpreterResolve.o"
	@echo "... AppMatch/AppMatch/CInterpreterResolve.i"
	@echo "... AppMatch/AppMatch/CInterpreterResolve.s"
	@echo "... AppMatch/AppMatch/CInterpreterResolveMatchSeletor.o"
	@echo "... AppMatch/AppMatch/CInterpreterResolveMatchSeletor.i"
	@echo "... AppMatch/AppMatch/CInterpreterResolveMatchSeletor.s"
	@echo "... AppMatch/AppMatch/CMatch.o"
	@echo "... AppMatch/AppMatch/CMatch.i"
	@echo "... AppMatch/AppMatch/CMatch.s"
	@echo "... AppMatch/AppMatch/CMatchCombinatoria.o"
	@echo "... AppMatch/AppMatch/CMatchCombinatoria.i"
	@echo "... AppMatch/AppMatch/CMatchCombinatoria.s"
	@echo "... AppMatch/AppMatch/CMatchListValid.o"
	@echo "... AppMatch/AppMatch/CMatchListValid.i"
	@echo "... AppMatch/AppMatch/CMatchListValid.s"
	@echo "... AppMatch/AppMatch/CParseAux.o"
	@echo "... AppMatch/AppMatch/CParseAux.i"
	@echo "... AppMatch/AppMatch/CParseAux.s"
	@echo "... AppMatch/AppMatch/CResultMatch.o"
	@echo "... AppMatch/AppMatch/CResultMatch.i"
	@echo "... AppMatch/AppMatch/CResultMatch.s"
	@echo "... AppMatch/AppMatch/CVariableGlobals.o"
	@echo "... AppMatch/AppMatch/CVariableGlobals.i"
	@echo "... AppMatch/AppMatch/CVariableGlobals.s"
	@echo "... AppMatch/AppMatch/CreateInstanceInterpreter.o"
	@echo "... AppMatch/AppMatch/CreateInstanceInterpreter.i"
	@echo "... AppMatch/AppMatch/CreateInstanceInterpreter.s"
	@echo "... AppMatch/AppMatch/InterpExecute.o"
	@echo "... AppMatch/AppMatch/InterpExecute.i"
	@echo "... AppMatch/AppMatch/InterpExecute.s"
	@echo "... AppMatch/AppMatch/InterpFunctionsCallcpp.o"
	@echo "... AppMatch/AppMatch/InterpFunctionsCallcpp.i"
	@echo "... AppMatch/AppMatch/InterpFunctionsCallcpp.s"
	@echo "... AppMatch/AppMatch/InterpreterListedFunctions.o"
	@echo "... AppMatch/AppMatch/InterpreterListedFunctions.i"
	@echo "... AppMatch/AppMatch/InterpreterListedFunctions.s"
	@echo "... AppMatch/AppMatch/InterpreterMatch.o"
	@echo "... AppMatch/AppMatch/InterpreterMatch.i"
	@echo "... AppMatch/AppMatch/InterpreterMatch.s"
	@echo "... AppMatch/AppMatch/InterpreterQuery.o"
	@echo "... AppMatch/AppMatch/InterpreterQuery.i"
	@echo "... AppMatch/AppMatch/InterpreterQuery.s"
	@echo "... AppMatch/AppMatch/InterpreterRelationEngine.o"
	@echo "... AppMatch/AppMatch/InterpreterRelationEngine.i"
	@echo "... AppMatch/AppMatch/InterpreterRelationEngine.s"
	@echo "... AppMatch/AppMatch/ParseAssertationSecondary.o"
	@echo "... AppMatch/AppMatch/ParseAssertationSecondary.i"
	@echo "... AppMatch/AppMatch/ParseAssertationSecondary.s"
	@echo "... AppMatch/AppMatch/ParseDictionary.o"
	@echo "... AppMatch/AppMatch/ParseDictionary.i"
	@echo "... AppMatch/AppMatch/ParseDictionary.s"
	@echo "... AppMatch/AppMatch/ParseListAux.o"
	@echo "... AppMatch/AppMatch/ParseListAux.i"
	@echo "... AppMatch/AppMatch/ParseListAux.s"
	@echo "... AppMatch/AppMatch/ParseRelation.o"
	@echo "... AppMatch/AppMatch/ParseRelation.i"
	@echo "... AppMatch/AppMatch/ParseRelation.s"
	@echo "... AppMatch/AppMatch/ParseRelationWhen.o"
	@echo "... AppMatch/AppMatch/ParseRelationWhen.i"
	@echo "... AppMatch/AppMatch/ParseRelationWhen.s"
	@echo "... AppMatch/AppMatch/ParseVerbs.o"
	@echo "... AppMatch/AppMatch/ParseVerbs.i"
	@echo "... AppMatch/AppMatch/ParseVerbs.s"
	@echo "... AppMatch/AppMatch/Parse_TokensGroup.o"
	@echo "... AppMatch/AppMatch/Parse_TokensGroup.i"
	@echo "... AppMatch/AppMatch/Parse_TokensGroup.s"
	@echo "... AppMatch/AppMatch/Parser.o"
	@echo "... AppMatch/AppMatch/Parser.i"
	@echo "... AppMatch/AppMatch/Parser.s"
	@echo "... AppMatch/AppMatch/ParserDynamicDispatch.o"
	@echo "... AppMatch/AppMatch/ParserDynamicDispatch.i"
	@echo "... AppMatch/AppMatch/ParserDynamicDispatch.s"
	@echo "... AppMatch/AppMatch/ParserPlural_table.o"
	@echo "... AppMatch/AppMatch/ParserPlural_table.i"
	@echo "... AppMatch/AppMatch/ParserPlural_table.s"
	@echo "... AppMatch/AppMatch/ParserSelectorFunctional.o"
	@echo "... AppMatch/AppMatch/ParserSelectorFunctional.i"
	@echo "... AppMatch/AppMatch/ParserSelectorFunctional.s"
	@echo "... AppMatch/AppMatch/ParserStmt.o"
	@echo "... AppMatch/AppMatch/ParserStmt.i"
	@echo "... AppMatch/AppMatch/ParserStmt.s"
	@echo "... AppMatch/AppMatch/ParserTextEntry.o"
	@echo "... AppMatch/AppMatch/ParserTextEntry.i"
	@echo "... AppMatch/AppMatch/ParserTextEntry.s"
	@echo "... AppMatch/AppMatch/Parser_A.o"
	@echo "... AppMatch/AppMatch/Parser_A.i"
	@echo "... AppMatch/AppMatch/Parser_A.s"
	@echo "... AppMatch/AppMatch/Parser_ActionControl.o"
	@echo "... AppMatch/AppMatch/Parser_ActionControl.i"
	@echo "... AppMatch/AppMatch/Parser_ActionControl.s"
	@echo "... AppMatch/AppMatch/Parser_ControlFlux.o"
	@echo "... AppMatch/AppMatch/Parser_ControlFlux.i"
	@echo "... AppMatch/AppMatch/Parser_ControlFlux.s"
	@echo "... AppMatch/AppMatch/Parser_Decide.o"
	@echo "... AppMatch/AppMatch/Parser_Decide.i"
	@echo "... AppMatch/AppMatch/Parser_Decide.s"
	@echo "... AppMatch/AppMatch/Parser_Plurals_En.o"
	@echo "... AppMatch/AppMatch/Parser_Plurals_En.i"
	@echo "... AppMatch/AppMatch/Parser_Plurals_En.s"
	@echo "... AppMatch/AppMatch/Parser_RegisterVerb.o"
	@echo "... AppMatch/AppMatch/Parser_RegisterVerb.i"
	@echo "... AppMatch/AppMatch/Parser_RegisterVerb.s"
	@echo "... AppMatch/AppMatch/Parser_VerbTable_en.o"
	@echo "... AppMatch/AppMatch/Parser_VerbTable_en.i"
	@echo "... AppMatch/AppMatch/Parser_VerbTable_en.s"
	@echo "... AppMatch/AppMatch/Parser_expression_match.o"
	@echo "... AppMatch/AppMatch/Parser_expression_match.i"
	@echo "... AppMatch/AppMatch/Parser_expression_match.s"
	@echo "... AppMatch/AppMatch/QueryItem.o"
	@echo "... AppMatch/AppMatch/QueryItem.i"
	@echo "... AppMatch/AppMatch/QueryItem.s"
	@echo "... AppMatch/AppMatch/RuntimeErrors.o"
	@echo "... AppMatch/AppMatch/RuntimeErrors.i"
	@echo "... AppMatch/AppMatch/RuntimeErrors.s"
	@echo "... AppMatch/AppMatch/StaticDispatchFunctions.o"
	@echo "... AppMatch/AppMatch/StaticDispatchFunctions.i"
	@echo "... AppMatch/AppMatch/StaticDispatchFunctions.s"
	@echo "... AppMatch/AppMatch/dynamicCast.o"
	@echo "... AppMatch/AppMatch/dynamicCast.i"
	@echo "... AppMatch/AppMatch/dynamicCast.s"
	@echo "... AppMatch/AppMatch/sharedCast.o"
	@echo "... AppMatch/AppMatch/sharedCast.i"
	@echo "... AppMatch/AppMatch/sharedCast.s"
	@echo "... AppMatch/AppMatch/stdafx.o"
	@echo "... AppMatch/AppMatch/stdafx.i"
	@echo "... AppMatch/AppMatch/stdafx.s"
	@echo "... AppMatch/AppMatch/testeLista.o"
	@echo "... AppMatch/AppMatch/testeLista.i"
	@echo "... AppMatch/AppMatch/testeLista.s"
	@echo "... AppMatch/AppMatch/testeSerialize.o"
	@echo "... AppMatch/AppMatch/testeSerialize.i"
	@echo "... AppMatch/AppMatch/testeSerialize.s"
	@echo "... AppMatch/AppMatch/teste_action.o"
	@echo "... AppMatch/AppMatch/teste_action.i"
	@echo "... AppMatch/AppMatch/teste_action.s"
	@echo "... AppMatch/AppMatch/teste_composition.o"
	@echo "... AppMatch/AppMatch/teste_composition.i"
	@echo "... AppMatch/AppMatch/teste_composition.s"
	@echo "... AppMatch/AppMatch/teste_selector.o"
	@echo "... AppMatch/AppMatch/teste_selector.i"
	@echo "... AppMatch/AppMatch/teste_selector.s"
	@echo "... AppMatch/AppMatch/teste_verb.o"
	@echo "... AppMatch/AppMatch/teste_verb.i"
	@echo "... AppMatch/AppMatch/teste_verb.s"
	@echo "... AppMatch/AppMatch/testesParser.o"
	@echo "... AppMatch/AppMatch/testesParser.i"
	@echo "... AppMatch/AppMatch/testesParser.s"
	@echo "... AppMatch/AppMatch/testes_1.o"
	@echo "... AppMatch/AppMatch/testes_1.i"
	@echo "... AppMatch/AppMatch/testes_1.s"
	@echo "... AppMatch/AppMatch/testes_2.o"
	@echo "... AppMatch/AppMatch/testes_2.i"
	@echo "... AppMatch/AppMatch/testes_2.s"
	@echo "... AppMatch/AppMatch/testes_Relation.o"
	@echo "... AppMatch/AppMatch/testes_Relation.i"
	@echo "... AppMatch/AppMatch/testes_Relation.s"
	@echo "... AppMatch/AppMatch/testes_decide.o"
	@echo "... AppMatch/AppMatch/testes_decide.i"
	@echo "... AppMatch/AppMatch/testes_decide.s"
	@echo "... AppMatch/AppMatch/testes_execute.o"
	@echo "... AppMatch/AppMatch/testes_execute.i"
	@echo "... AppMatch/AppMatch/testes_execute.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

